### ISSUE TITLE
Filer: Can't move to a note without headings

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#10]
Filer is GREAT. One little edge case I ran into: I migrated a lot of notes from Obsidian. Many don't have headings (they're just notes), so if I try to move a task to a file without headings, Filer gets stuck on the "Pick a heading" step. If there are no headings, I guess it should ask whether you want it at the top or the bottom of the note. Heck, now that I mention it, when you list out the headings even when there are some, maybe you ask if they want to move to:
```
(top of note)
heading foo
heading bar
(bottom of note)
```

@jgclark

**Comment by jgclark** [comment]
@dwertheimer Should be fixed in acfceaebfab92c677b630a3505cf199cfe9c5fff, released in a moment as v0.2.2. Please test and close if possible.

**Comment by dwertheimer** [comment]
Works great!
