### ISSUE TITLE
Refactor helper files to split NP-dependent code from pure Javascript code

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#105]
Discussion from Discord here: https://code.visualstudio.com/docs/editor/refactoring

Spies/mocks are Phase 2 in my opinion. Phase 1 is to break out helper functions that are pure JS functions (no Noteplan calls at all) and put them in their own file so that we can include them in files we are Jesting. Right now, I have an array-of-objects sorting function that I want to use in two different plugins. So I copied it to the helpers/general file, but when I try to include that function, I get all the DataStore errors from other functions in that helpers/general file. So I was thinking that we probably should rename whatever helper files which have NP-specific dependencies (e.g. NPGeneral.js) then I could put things like my sorting function into a non "np" file, e.g. helpers/general. There are some files (e.g. helpers/dateTime.js which are already pure -- no NP-specific code in there. 

codedungeon:
Yep, a file prefix would be fantastic change (and it is how I use it myself for all my various "helper" functions).   If the code uses NP API in any capacity, the filename starts with NP (e.g., NPNotification.js)  

So for example, we are going to move `helpers/general.js` to `helpers/NPGeneral.js` and pull any of the pure, non-NP specific code into `general.js`. However, we are going to try to limit the amount of stuff in `general` and prefer to create specific files which have specific functions. e.g. `helpers/userInput.js` -> `helpers/NPUserInput.js` (pretty much all of the functions there are NP-specific)

**Comment by jgclark** [comment]
I wanted to discuss here, as I remember @mikeerickson's previous comment about him changing quite a lot of code in an unspecified existing file, in his work towards Templating. Is that a helper file? Do you have other new conventions around naming and testing that we'll see when you release it? If so, let's be aware of that while we're making changes.
I've also been trying to add more documentation headers to existing functions, but there are quite a few more to do. I will attempt to do some more of that in whichever files I work on.
