### ISSUE TITLE
A plugin to create Week/Month/Quarter folders/files from a template you choose

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#108]
I was thinking based on @bderuyck workflows that it would be cool for someone to write a plugin which creates a year folder with a file for each quarter and week in it. e.g.
2021/Weeks/02 2021-02-02 - 2021-02-08 
and
2021/Months/01 January 2021
and
2021/Quarters/Q1 2021-01-01 - 2021-03-31
(using a template you choose) 

Discord discussion:
https://discord.com/channels/763107030223290449/910825679782821909/910975217881452584

**Comment by dwertheimer** [comment]
Assigning @jgclark because he said he wanted to think about it :)

**Comment by jgclark** [comment]
Unassigning me. I thought my suggestion was that we ask @EduardMe about this first, as IMHO this is close to an item on his published roadmap.
But I have lots of relevant code in the Summaries plugin ...

**Comment by aaronpoweruser** [comment]
Closing as week, month, quarter and yearly notes are supported natively in noteplan now.
