### ISSUE TITLE
jgclark.Reviews plugin - project list not using tags in _configuration

### ISSUE THREAD

**Issue by mikeerickson** [NotePlan/plugins#137]
**Describe the bug**

As reported here

https://discord.com/channels/763107030223290449/784376250771832843/917489575142752277

User is reporting the `Reviews/project list` file is not created.  I have managed to track down the file and it is indeed created (at least on my environment) but I have found the `tags` defined in `_configuration` file are not used, it always uses the default tags.

```json     
  review: {
    folderToStore: "Reviews",
    foldersToIgnore: ["📋 Templates", "Reviews", "Summaries"], // can be empty list
    noteTypeTags: ["#test", "#test1"], // array of hashtags without spaces
    displayOrder: "alpha", // in '/project lists' the sort options  are "due" date, "review" date or "alpha"
    displayGroupedByFolder: true, // in '/project lists' whether to group the notes by folder
    displayArchivedProjects: true, // in '/project lists' whether to display project notes marked #archive
  }
```

**To Reproduce**
1. Go to `_configuration` file and add one or more tags (don't use default tags)
2. Add these tag(s) to any note
3. Invoke `/project list`
4. Review created note'

**Additional Steps**
1. If default tags are added to note (e.g., #project #area) then the project list will be populated correctly

**Expected behavior**
`Reviews/project list` is created and populated with defined tags.

**Screenshots**
```markdown
# #project List
Last updated: 12/7/2021, 2:19:05 PM
Total: **1 active notes**
_Key:	Title	# open / complete / waiting tasks / next review date / due date_
### - 🛠 Projects/<redacted>/2021-12 (1 notes)
- [[2021-12-07 Standup]]	o0 / c0 / w0 / - / -
```

**System**
 - Device: Any
 - OS: macOS Monterey
 - NotePlan Version 3.3 (676)
 - jgClark.Review 0.9.0

**Additional context**
The method is executing and traversing correctly, this can be seen in the plugin console, but it will never find the defined tag(s).

**Comment by jgclark** [comment]
It is not expected behaviour to populate `Reviews/project list` with defined tags.
Rather, in the example given, I would expect `Reviews/test List` and `Reviews/test1 List` to be created and populated.

**Comment by jgclark** [comment]
However, I have now found a missing 'await' in the call to `getConfig()` which could result in tags getting ignored.
