### ISSUE TITLE
jgClark.Review note name does not match filename

### ISSUE THREAD

**Issue by mikeerickson** [NotePlan/plugins#138]
**Describe the bug**

In addition to the previous issue (https://github.com/NotePlan/plugins/issues/137), I have discovered that when the `project` method is executed, it creates unique note filenames (as observed in finder) but the associated note title remains the same "project List" each time, thus appearing as there are duplicate notes

**To Reproduce**
1. Execute `project` command multiple times
2. View the created notes in the `Reviews` folder

**Expected behavior**
I feel it will be better if the new note title should match that of what is stored on disk (e.g. project List, project List 2, etc)

**Screenshots**
![CleanShot 2021-12-07 at 14 37 05](https://user-images.githubusercontent.com/183153/145116673-5f16eadd-21b5-45e0-830b-d5f0a8236f71.png)

![CleanShot 2021-12-07 at 14 37 37](https://user-images.githubusercontent.com/183153/145116734-b7e7196d-53b0-4350-bf93-e74ae329406e.png)

**System**
 - Device: Any
 - OS: macOS Monterey
 - NotePlan Version 3.3 (676)
 - jgClark.Review 0.9.0

**Comment by jgclark** [comment]
I realise I'd fixed this a month ago in 0.4.3 but never released the update it for some reason. New 0.4.4 release should include that fix.
