### ISSUE TITLE
Supporting 'unofficial' repositories

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#16]
We've had a little chat already about supporting a wider range of plugin sources than just this repo. Indeed I believe @nmn is working on a npm-based suggestion.

Now IanL @phyward has a first very industry-specific example for us to think about:  https://github.com/phywand/pmlNotePlan.

So creating this issue to be a place to discuss our options further.

**Comment by dwertheimer** [comment]
@jgclark I think we should close this issue as duplicate and put all the discussion under one roof on the NPM thread (maybe rename that title to be the same as this one -- less about the how and more about the goal) 
https://github.com/NotePlan/plugins/issues/6#issuecomment-877652946

**Comment by jgclark** [comment]
OK, doing as @dwertheimer suggests, and closing in favour of #6.
