### ISSUE TITLE
Fix bug in .addParagraphBelowHeadingTitle() with missing headings

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#184]
`.addParagraphBelowHeadingTitle()` has a bug.
Where the heading is missing it adds an extra `# ` before the title, rendering it e.g. `# ## New heading`.

This can be seen in the QuickCapture plugin (/qaj: Quickly append text to today's journal).

(Reported 2021-09-18)

**Comment by jgclark** [comment]
Bumping this up in priority, @EduardMe, as its now affecting 4 of my plugins, and I guess it's a simple fix.

**Comment by EduardMe** [comment]
I have actually fixed it, but have not released the next alpha/beta yet. Moving it to the done column.

**Comment by jgclark** [comment]
I've checked this has been fixed. Thank you.
