### ISSUE TITLE
CommandBar.textPrompt not working on iOS, iPadOS

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#185]
const ret = await CommandBar.textPrompt('title', 'message', 'default')

Works as expected on macOS

**Comment by EduardMe** [comment]
Do you have a full sample plug-in package? For me this single command works for me on iPhone.

**Comment by mikeerickson** [comment]
After Eduard was able to run the sample plugin I sent him and all things worked, I thought to maybe try rebooting the device.

Rebooted iPhone and ran test plugin and all (6) dialogs were displayed successfully.  

Pretty weird that a phone reboot (but also a NotePlan reboot) was the actual fix?

**Comment by mikeerickson** [comment]
I attempted to apply same approach on iPad, but the crashing still occurs.

- restarted iPad
- Reinstalled NotePlan from TestFlight

Using the same plugin, it crashes as soon as it hits `CommandBar.textPrompt`

- iPadOS 15.0.2
- NotePlan TestFlight 3.3.2 (719)

**Comment by mikeerickson** [comment]
Not quite sure what i did, but it is not working on iPad and I am unable to break it, so I guess we can close this issue and hope things stay working :-)
