### ISSUE TITLE
Create _config Migration Function

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#186]
_configuration + plugin.json -> settings.json

@codedungeon: If we don't have any takers on this one, I can do it.  I have already written a fair amount of conversion code already as I  prepare np.Templating.

**Comment by EduardMe** [comment]
I can let NotePlan call a `migrate()` function upon update or install as a "hook" more or less, so the plugin can react to changes without having to check upon execution. Would this work?

**Comment by jgclark** [comment]
Without sketching out a full design, I can't be certain. But I think it's 98% likely this will work.
Note, though, that the behaviour will be quite different if this is a first install (where there won't be any settings to _migrate_ but will need _populating_) rather an update (where there is either migration from ConfigV1 to ConfigV2, or a possible update to plugin.settings). So perhaps set up two hooks: `populateSettings` and `migrateSettings`?

**Comment by jgclark** [comment]
I'm calling this one complete, as its been a week or more since we did the bulk of the migration testing, and no issues with the migration function have emerged.
