### ISSUE TITLE
Plugin triggers

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#187]
Start the plugin command triggering architecture and implement one trigger (onNoteOpen or onDayStart?).
(DW called this 'hooks', but I'm avoiding that term to avoid confusion with the separate app Hook.)

_This was discussed at Plugin Dev meeting 1, and there should be some notes from that available._

**Comment by mikeerickson** [comment]
@jgclark @EduardMe @dwertheimer These are referred to as events/hooks in React and Vue, so I suppose we can relabel as "events" to not confuse the reference to Hook as outlined in original message)

**Comment by dwertheimer** [comment]
I would like to suggest we come up with a generalized pub/sub architecture
for this. We also should think about building in profiling/timing because
too many subscriptions and long processes could block the app or make it
feel sluggish.

**Comment by EduardMe** [comment]
We had a brief discussion how this could be like, inspired by Apple's way of handling permissions to for exampel Reminders:

- Plugin declares in the `plugin.json` which permission it needs and the Javascript function which should be called (similar to the commands).
- The user gets prompted with a permission dialog after install/update.
- Inside the plugin preferences (probably in the dropdown of each individual plugin), the user can change the permissions afterward. Only the permissions the plugin registered for are listed with checkboxes.

Ideas for use cases, I came across so far:
- Insert a template automatically, when you create the note for tomorrow (onNewNote)
- Move completed tasks to the bottom of the list (onTaskCompleted)

**Comment by dwertheimer** [comment]
We should (somewhere) keep a list of potential events/hooks so they can be prioritized. I will get it started, but this list is not exhaustive. Is there a better place to keep this list?

- onNewNote
- onTaskCompleted
- onTaskCreated
- onTaskDeleted
- onTimeBlockCreated
- onCalendarEventCreated
- onCalendarUpdate
- onDayChanged
- onHourChanged

...pls add to the list...

**Comment by jgclark** [comment]
I'm with @EduardMe's suggestions above about permissions and use cases. Other use cases related to others on @dwertheimer's list:
1. run my more advanced @repeat() processing within a note (onTaskCompleted)
2. run clean-up, including archiving within a note (onHourChanged)
3. add monthly/quarterly/yearly review notes (onDayChanged)
4. update a background counter on new tasks created per day (onTaskCreated)

For time-based triggers (onDayChanged, onHourChanged) there's a design question about what happens when NP isn't running when those events fire. This is akin to some periodic user processes you can register in macOS. You can ask for them to fire when NP is next run -- which I think makes sense for onDayChanged. Or sometimes you can say 'keep just the latest one' which might make sense for onHourChanged, if that behaviour was clear. In my second example above, this is what I think should happen. It doesn't matter when it runs, as long as it runs fairly frequently.

There's also the design question of what data is made available when the trigger fires. I suggest:
- onNewNote(TNote)
- onTask*(TNote, TParagraph)
- onTimeBlockCreated(TNote, TParagraph, DateRange)
- onCalendar*(TCalendar) -- does it need TNote as well?
- onDayChanged(Date)
- onHourChanged(Date) -- includes time, if that's critical

For the time based triggers it would be helpful to have an API call along the lines of `notesChangedSince(datetime: Date): <TNote>`. That saves traversing the DataStore frequently by clean-up routines.

The alternative is to have another trigger:
- onNoteChanged(TNote)
but the challenge with this is not triggering too frequently. Look at the number of note revisions that are created; I would suggest something like a minute's time-out before a new revision and onNoteChanged trigger was fired.

**Comment by wizzard0** [comment]
I see an exciting line "Plugin triggers (simple)" in 3.7.2 910 description; is there a doc somewhere?)
([crosslink](https://discord.com/channels/763107030223290449/809886801857871883/1043301440464093264))

**Comment by EduardMe** [comment]
Just added: https://help.noteplan.co/article/173-plugin-note-triggers

**Comment by dwertheimer** [comment]
@EduardMe  can you pls make it possible for there to be  arguments passed to these triggers in the frontmatter? I want to have different kinds of onEdit functions depending on the content, and I don't want to have to create exported commands for all of them.

**Comment by jgclark** [comment]
Incidentally, I'd been leaving this one open, not so that DW can pile more in (!) but because I thought you said you were going to rename the first trigger. Or did I misunderstand?

**Comment by dwertheimer** [comment]
Yes, I don't see the notes from the call but @EduardMe has them. @EduardMe pls update the task name so we're clear on what we're trying to accomplish here now.

I think the goal was to end up with: onSave, onOpen (and maybe onEdit) for starters
There was going to be some trapping to try to keep infinite loops from happening. I found that I created infinite loops twice already. Here's some code I wrote to get around them:

```js
/**
 * When note is opened, check if it's been awhile and if so, reload the contents
 * Triggered on open using:
 * triggers:	onOpen => np.ThemeChooser.onOpenRefreshPage
 * @param {*} note
 */
export async function onOpenRefreshPage(note: TNote): Promise<void> {
  try {
    const now = new Date()
    if (Editor?.note?.changedDate) {
      const lastEdit = new Date(Editor?.note?.changedDate)
      if (now - lastEdit > 30000) {
        const refresherPara = note.paragraphs[1]
        note.removeParagraph(refresherPara) // try to keep circular refresh from happening
        // do not refresh unless it's been at least 15 seconds since the last
        logDebug(pluginJson, `onOpenRefreshPage ${timer(lastEdit)} since last edit. auto-refreshing page`)
        await createThemeSamples('', true)
      } else {
        logDebug(pluginJson, `onOpenRefreshPage ${(now - lastEdit) / 1000}s since last edit, not refreshing`)
      }
    }
  } catch (error) {
    logError(pluginJson, JSP(error))
  }
}
```

**Comment by dwertheimer** [comment]
Even with this code, I found myself in a loop because inside my plugin which is running, I was opening the document before writing to it. (if the /plugin command is run from the command bar, it needs to open the document). That open was causing the autoRefresh to happen infinitely before a file could get written to update the lastUpdated date. So I had to make sure that I wasn't in the document already...probably a good idea regardless but wasn't bothering me before the trigger:

```js
    if (Editor?.note?.filename === filepath) {
      // Don't reload the file if we are already in it
      note = Editor
    } else {
    ...
}
```

**Comment by dwertheimer** [comment]
So yeah, to quote @EduardMe
> With great power comes great responsibility

**Comment by dwertheimer** [comment]
BTW, in doing some of this development, I'm reminded of a discussion we had with @nmn and two triggers that could be helpful would be: `onFocus` (someone comes back to the app or this tab/pane and the document is in foreground) and `onBlur` which is the opposite (you were in it and not in it anymore).

So here's the running list I culled from above [and not yet prioritized beyond the first 3]:
- onOpen
- onSave (file written)
- onEdit (keystrokes)
- onNewNote
- onTaskCompleted
- onTaskCreated
- onTaskDeleted
- onTimeBlockCreated
- onCalendarEventCreated
- onCalendarUpdate
- onDayChanged
- onHourChanged
- onNewNote(TNote)
- onTask*(TNote, TParagraph)
- onTimeBlockCreated(TNote, TParagraph, DateRange)
- onCalendar*(TCalendar) -- does it need TNote as well?
- onDayChanged(Date)
- onHourChanged(Date) -- includes time, if that's critical
- onFocus
- onBlur

**Comment by dwertheimer** [comment]
w/r/t arguments, i think we could do something like this:
```
  triggers:	onOpen => np.ThemeChooser.onOpen(refresh,30)
```
 and you could just use regex or split to separate out the function from the variables in parentheses and pass those arguments through to the function named

**Comment by jgclark** [comment]
Closing this, as the original aim (of a first trigger to exercise the new architecture) has been met.
