### ISSUE TITLE
Add info button to plugin list in preferences to open the drop-down

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#188]
As many people don't see the caret.

**Comment by EduardMe** [comment]
You can also click anywhere on the plugin title now, not just the caret.

**Comment by dwertheimer** [comment]
Great. I agree with Jonathan. Should close when clicked again.

**Comment by EduardMe** [comment]
Should already work in the alpha. You can also click anywhere on the plugin name now to toggle it. Closing this issue.
