### ISSUE TITLE
Finish Configuration UI

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#189]
For now include a scrollable text box for object definitions. Will include basic JSON validation, and conform to HIG where known!

**Comment by jgclark** [comment]
I can't tell what you have fixed and what is pending. The ability to tab through the fields is the most important, but I'd be happy for that to be in a follow-up release.

**Comment by EduardMe** [comment]
Tabbing through the fields has a problem with text fields. The JSON text field should support tabs? And the other text fields may be too, I'm not sure, but I have enabled it for all.

**Comment by jgclark** [comment]
I think it's right that JSON needs to include tabs. But I would disable them for the others.
<thinks>
Some people are using tabs as interim mechanism before you can bring tables in. Therefore perhaps we need to allow tabs in all text fields after all.

**Comment by jgclark** [comment]
Closing this as #215 is now a superset.
