### ISSUE TITLE
Plugin Settings - Heading Section Not Displayed

### ISSUE THREAD

**Issue by mikeerickson** [NotePlan/plugins#195]
**Describe the bug**

The `Heading` section is not displayed in Settings Editor

Take the `jg.DailyJournal` plugin as an example.  With the heading defined as

```json
{
    "type": "Heading",
    "title": "Daily Journal settings"
}
```

It does not appear in the dialog

**Expected behavior**
Should appear as defined in `plugin.settings` specification

**Comment by EduardMe** [comment]
It's case sensitive, try `"heading"`. I checked briefly, but I'm not sure if I can easily change it to non-case sensitive. At least not at first look.

**Comment by mikeerickson** [comment]
@EduardMe Indeed, the `heading` label fixed the issue
