### ISSUE TITLE
/nc doesn't work for me (the others do). When you select /nc it just disappears. Even after restart

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#2]
No logging in console, so I don't know what else to tell you, but happy to help track it down.

**Comment by jgclark** [comment]
That's odd. This is the first report of this. 
What OS(es) have you tried this on, and what storage type?
(There's no console logging for this particular plugin command, as its a simple one.)

**Comment by dwertheimer** [comment]
Plugin command dies when trying to access `Calendar.unitsAgoFromNow` which doesn't seem to exist.

I added some console.logging to locate the problem. Here are the results:

```
typeof Calendar = [object NotePlan_3_Beta.CalendarBridgeConstructor] //good
typeof Calendar.add = function //good
typeof Calendar.unitsAgoFromNow = undefined //bad -- this one is used in the code
typeof Calendar.timeAgoSinceNow = undefined //also bad, so it's not just one function missing
```
on Mac OSX 10.15.7
Noteplan 3 Beta - Version 3.0.21 (630)
Using SSD & Cloudkit

@EduardMe

**Comment by jgclark** [comment]
Excellent report, thanks.
These date functions were added only recently, and from memory either in
build 630 or build 631.
I see you're on build 630; I'm on build 631, and I thought that was the one
@EduardMe made public yesterday.

**Comment by dwertheimer** [comment]
Ah...interesting. I guess the plugins should probably have some minimum App version compatibility requirement in order to load/run. 
I don't know how to get 631. I only have 630 that @EduardMe emailed me a link to. Is there a place to download the always-latest build? I notice that the "Check for updates..." doesn't work for this.

**Comment by EduardMe** [comment]
Oops, sorry! Are you on Discord? I'm usually releasing betas in the #releases channel. That's the best way to get them. The internal updater has some hiccups due to Sandboxing. Here is the link to Discord in case you are not a member yet: https://discord.gg/D4268MT.

Alternatively, here is the download link: http://noteplan.co/download/NotePlan-3-Beta-631-AppStore.zip

**Comment by EduardMe** [comment]
However, @jgclark I have also seen some of the statistics plugins disappearing. Running it a few times I got it staying open. Not sure what it was, but I have it on my list. Might be I need to run it through the debugger live with XCode if I get this reproduced regularly.

**Comment by jgclark** [comment]
Thanks. There is a minimum app version check built into the plugins, but it
only operates at version number not build level. In retrospect perhaps this
series of betas should have been 3.1.x not 3.0.x ...?

**Comment by dwertheimer** [comment]
Closing. Works on upgrade to 631
