### ISSUE TITLE
Plugin Settings: Create Hidden Item

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#201]
Maybe this is an edge case, but I have some settings that I want there to be a line in the JSON config for (and I want to be able to change in my plugin.json), but I don't want users to be able to change the setting in the Plugin Settings interface. Would be good if you could add a property to the config spec called "hide".

**Comment by jgclark** [comment]
For now, you could always use the existing method to save/load a Preference. It's not as clean to be using 2 different mechanisms, but I'm using it for something hidden.

**Comment by mikeerickson** [comment]
@jgclark While this is true, we can manage this in code using the API, but as soon as the `settings.json` is edited using NotePlan Configuration VIew, it blows out everything that is NOT in the `plugin.json:plugin-settings`

**Comment by EduardMe** [comment]
If you use a filename, you can save settings using `DataStore.saveJSON(object, “some filename.json”)`, which should not be overwritten by the plugin configuration. Only the default one gets overwritten.

**Comment by dwertheimer** [comment]
Yes, but is a lot of extra steps and room for error (reading, merging,
etc).

 type=‘hidden’ seems like it would take less time to implement than it took
to respond to this thread. @eduardme in your loop, just ignore it in the
settings sheet but keep it in the data structure for writing.

**Comment by EduardMe** [comment]
Here's what I have tested:

```javascript
  console.log("the hidden value: " + DataStore.settings.hiddenKey)
  let settings = DataStore.settings

  // Will save it, but if the user saves the settings again, this will result in "undefined"
  settings.hiddenKey = 100 
  DataStore.settings = settings
```
