### ISSUE TITLE
How to deal with config for plugins which import other plugin functions?

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#202]
In my autotimeblocking plugin, I wanted to make it possible for the time blocks to get written to the calendar automatically. Since @jgclark had already written code to do this in his EventHelpers plugin, I imported it. I now call EventHelpers (which has its own set of config settings) from within my plugin. This works fine today because his plugin code gets rolled into my plugin and when it's invoked, it gets *or creates* the config it needs. Someone doesn't even have to have downloaded or run his plugin ever because my plugin includes his plugin code. I don't know for sure, but my suspicion is that this will break down with configV2 since his configuration settings are not included in my plugin.json. So what will happen? I'm not sure, but I'm a little concerned. More importantly, how shall we work around it?
BTW, this may also be true of Templates which include functions from plugins (there are a million examples) which may have not been installed or configured.
Is this going to be an issue or do we already have a plan for how to work around it? Hopefully, I'm worried for nothing. :)

**Comment by jgclark** [comment]
Just a brief response as I'm triaging new issues ...

I think at dev meeting 1 we agreed that each plugin would have its own private settings file, **but** that there were valid reasons for being able to break out of that and read other files in the NP sandbox.  I suspect the new pair of ...Settings() functions won't be able to do that, but `loadJSON()` deliberately can. ("Load a JavaScript object from a JSON file located (by default) in the <Plugin>/data folder. But you can also use relative paths: ../Plugins/<folder or filename>.")

So there's a hack-y way around this, but I agree this needs some thought for a 'proper' solution.

**Comment by dwertheimer** [comment]
True @jgclark. Yes, trying to avoid the hacks. Will also be interested to know what @mikeerickson plans, since I think this will affect Templates as well and maybe he's already thought about it.

**Comment by dwertheimer** [comment]
@jgclark Maybe the smartest, cleanest solution here would be to break the eventsToCalendar functions out, put them all in a helper file and pass the config as a param. I actually think you had mentioned wanting to do this awhile back. So that way, as long as I pass in the requisite config params that the function needs to operate, we don't need to deal with this.

...and maybe as @m1well suggested, this is a good moment to stop allowing plugins to import from other plugins (especially when they need config). Shared items should be helpers or NPshared (or something). Speaking of which, getOrMake needs to be a helper, not living in Templates...

**Comment by jgclark** [comment]
That's all good, and nicely builds on earlier intents, some of which have yet to happen.
In fact, then, here are new rules for plugin authors:
- plugins shall not import code from other plugins. Shared functions/types/constants should live in helpers/*.js.
- helper functions shall live in files under the helpers/ folder. Any that use NP functions shall live in a NP<topic>.js file; those that don't live in the <topic>.js file.
- new functionality should be provided using a series of discrete functions (and their equivalents), which are then linked together as required by lightweight wrapper functions which can then be exposed as commands available through the plugin menu (and / mechanism), as well as through Template calls.
- <something yet to be determined about how to offer and integrate new functions to the Templates/Templating system>

Your comments are requested, @m1well @mikeerickson @dwertheimer.
Then Mike or I can add to the documentation.

**Comment by jgclark** [comment]
Hmm, actually I've thought of an exception already. It's the problem I raised way back at #11 ... that there is tight coupling between nmn.Template and any plugin that provides {{commands}} used in Templates.  I've remember this, because I have a new function I want to use in this way.
As I don't know the details of Templating v2, I don't know whether this issue will go away.

**Comment by jgclark** [comment]
FYI d772ed56591e3707ebe3ce87e90455bdeed3a6d2 is related: starts split of helpers/dateTime.js into helpers/NPdateTime.js as well. But I've left copies in helpers/dateTime.js so nothing breaks for your code. Over time I'll do some PRs to finish this off.

**Comment by m1well** [comment]
> * plugins shall not import code from other plugins. Shared functions/types/constants should live in helpers/*.js.
yes that is what I said some times now and what I meant with `api style code`. we developer rather talk about an api than many helper functions - because on some time there are more `helpers` than real code - and `helpers` is a bit - let's say "under value" for some important functions with notes oder paragraphs - in my opinion.

> * helper functions shall live in files under the helpers/ folder. Any that use NP functions shall live in a NP.js file; those that don't live in the .js file.
of course you can argue about the names, that is a matter of taste. but as I said - NP code and "helpful core functions" like moving/sorting paragraphs or a selection should become an "api" and all other code like date conversions or number conversions etc. should become or stay as helpers.

> * new functionality should be provided using a series of discrete functions (and their equivalents), which are then linked together as required by lightweight wrapper functions which can then be exposed as commands available through the plugin menu (and / mechanism), as well as through Template calls.
I hope I understand it correctly -> but yes 100%

> * <something yet to be determined about how to offer and integrate new functions to the Templates/Templating system>
they are also just wrapper. sou you just call the new "api" function with parameters

**Comment by jgclark** [comment]
@m1well I'm glad I've now expressed your 'api style code' point in a way that I can understand.  You have my respect for working on this despite English not being your first language, and I'm grateful for your patience as we work out what each other mean.

I'm still not sure about the difference you see between API and helpers.  The way I understand it, only Eduard can write the NotePlan API. But we can write helpful things on top of the API.  We've made various requests over time for new API calls, and Eduard has done many of them. I've added more in recent days, and you can as well, by raising issues and tag them API + enhancement.

> > <something yet to be determined about how to offer and integrate new functions to the Templates/Templating system>

> they are also just wrapper. sou you just call the new "api" function with parameters

I hope so, but it will depend on how @mikeerickson has implemented Templating.  The current Templates system is **not** as simple as this, as I explained back in #11.

**Comment by dwertheimer** [comment]
From Discord thread: https://discord.com/channels/@me/928678751808671865/940386260034412614 

I think we should also make a version which returns the entire settings.json file contents (object) for a given plugin name. Yes, it's just the line of code I gave to @jgclark, but it will be wrapped by try/catch and deal with the file not existing etc. So, to riff on Mike's version above, something like:
` export function getSettings(pluginName?: string = ‘’, defaultValue?: {[string]:mixed} = null ) :  {[string]:mixed} | null`
BTW, the nice part of having a function for this is that we could make it so that this function effectively does what NotePlan settings is doing:
a) returns the settings.json if there is one, or 
b) returns the defaults otherwise (supplied to it in the defaultValue) 
Note that I did not say "returns the defaults from that plugin's plugin.json", because of the thorny edge case... when I read in the Templates doc about some cool command that comes from a jgclark plugin (e.g. jgclark.QuickCapture), and then I try to run it without actually having that plugin installed. So there's no way to get at it's settings.json or even its plugin.json
But in the call to getSettings, I am supplying the default object, and so I know I will have something useful to use.

I proposed it because of the use-case you found the other day. 🙂
You were running a template that called a function in jgclark.EventHelpers (or whatever). The work-around I gave you worked only because:
a) you had the jgclark.EventHelpers plugin installed, and 
b) the settings had been migrated already (it had been run), so there was a data/jgclark.EventHelpers/settings.json file
If either (a) or (b) had not been true, even the workaround would have failed 
I assume that people will sometimes read about things in the Templates plugin and try to use them. The functions are there because they get rolled into Templates. But the plugin.json and config settings file may not necessarily be there
So the defaults are a work-around for that
The alternative, and maybe it's a better one, is:
a) if the helper which tries to load the config file returns null to
b) stop and tell people they have to download and run the XXX plugin before this template command will work. But that means popping up this message in the middle of a template run and somehow stopping execution
[@jgclark liked this solution better]

This is not for now, but something to put on the board for the future,  now that @codedungeon has written this plugin downloader, what if, in the case the helper doesn't find the config file for the plugin, it calls the downloader and installs the needed plugin so that the file will be there? Again, not for today. But food for thought.
On a totally unrelated note, @jgclark would you be willing to put "add a command bar button to the first page of menubar controls on iOS" on the board near the top (and encourage Eduard to do it)? It feels like something that gets talked about in the forum from time to time and then forgotten. For me, it's my #1 feature request

Mike said:
It would sure be nice if there were a XXXX.installPlugin method.  Further, I am trying to figure out how I can check if a plugin is installed and at least provide a notification that a plugin dependency exists XXX.checkPlugin

**Comment by jgclark** [comment]
Just a note from yesterday's experience: current Template uses _whatever version of other plugin's commands were available when it was compiled and released_. **Not** whatever the most recently-installed version of the other plugin is (if indeed it is installed).

**Comment by dwertheimer** [comment]
@jgclark is this still needed? From my perspective, I have found enough workarounds that I think we can close it.

**Comment by jgclark** [comment]
Yes, I think we're beyond this now.
