### ISSUE TITLE
Summaries Plugin - saved search highlights inside links

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#207]
@jgclark I don't know if you would consider this a bug or not, but you may want to deal with it anyway:

When highlighting is turned on and the term is found inside a URL or a link title, the highlighting breaks the links in a couple of different ways:

In these examples, I searched for "tennis":

In this example, the highlighting is not even visible in the Editor, but the link is re-written and now will 404 when clicked:
![Screen Shot 2022-01-16 at 8 09 30 AM](https://user-images.githubusercontent.com/8949588/149667954-e6fb9d69-ccf0-45c3-9c6d-7b3f60388123.jpg)

In this example, the text is found in the path to the attachment:
![Screen Shot 2022-01-16 at 8 09 49 AM](https://user-images.githubusercontent.com/8949588/149668019-2be925d3-074b-433d-85ad-3a75db769f25.jpg)

**Comment by dwertheimer** [comment]
These may be edge cases that are not worth your effort to fix, but I thought I would let you know so you could keep an eye out anwyay.

**Comment by jgclark** [comment]
Hmm, I see the problem.
I suppose the first question is whether you want search to match on terms in URLs etc.?
Assuming yes, then there's a bit of regex-based defeating to do. Could we safely assume a search term won't get split partly inside and partly outside a URL etc.?

**Comment by dwertheimer** [comment]
yes

**Comment by jgclark** [comment]
Final test, please, @dwertheimer to check your most recent Templates update hasn't got upset in the process.
