### ISSUE TITLE
Requests for rollup process

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#21]
A couple of requests to make @nmn's process even better:

1. watch/autowatch should detect changes to the `plugin.json` files, as well as the `*.js` files.
2. watch, not just autowatch should copy the resulting new file to the live local `Plugins` directory (if `.pluginpath` is set up). [The reason I mention this is that autowatch doesn't seem to report if its work doesn't complete. There have been times where I've had a significant error in the JS, and so the plugin hasn't been updated, but it gives no indication of this. So I run watch:plugin instead, so I can see whether there are errors.]
3. review how much gets included in the rolled-up output `script.js`.

The last is because I'm surprised just how big the resulting rolled-up `script.js` files get. Instead of say 10kb of code that we write, it becomes >250kb. I know it will need to get larger, but I can't believe it needs to be this much larger. It's not a big deal with fast internet and processors, but we should be trying to reduce CPU load.

**Comment by dwertheimer** [comment]
I can't speak to the size increase and what's being added in, but maybe the script can minify the code at the end. As long as the entry point name is not modified, everything else can be minified (at least for the #release version). That could reduce file size by > 50%

**Comment by dwertheimer** [comment]
@nmn ^^^

**Comment by dwertheimer** [comment]
Looks like about 50% of the code in your plugins is PEG.js for parsing and the majority of the rest is YAML, JSON5 and other specific parsers -- so basically all the code is going to parsing. Maybe since this parsing code is going to be used in a variety of plugins, it should be pulled into the API? @EduardMe @nmn

**Comment by nmn** [comment]
Yup, the three parsers add a considerable amount of code and I assumed this would be temporary as Noteplan would eventually add a configuration API. In the meantime, we could greatly improve things by removing support for YAML and TOML and using only JSON5.

As for minification, it's an easy change to make, so I'll do that soon.

**Comment by jgclark** [comment]
I know I was happy to see TOML and YAML options, alongside JSON5. But now I've been writing the mechanism to populate some default configuration data into the `Templates/_configuration` file if the plugin command needs it, I've limited it to just JSON5 syntax. So, actually, I'd be happy with restricting this to being just one format type.
(I find the JSON5 format the fiddliest of the three, but will use whatever the consensus is.)

**Comment by nmn** [comment]
I just noticed the mention of a lack of error reporting by `autowatch`. This should be easy enough to fix. I want to get to a place where the `autowatch` command takes care of all use-cases. The idea is to make the process of contributing as dead simple as possible.

**Comment by dwertheimer** [comment]
@nmn In order to keep autowatch from rebuilding every plugin, the script.js
file modified date/time should always be greater or equal to the latest .js
file's modified date/time. So can autowatch/rollup just compare those times
and only invoke a rebuild when the .js files are newer than the script.js
file?

**Comment by jgclark** [comment]
@dwertheimer I've just spotted a flow error in rollup.js from your (newish) line `const { program } = require('commander')` as it doesn't recognise 'commander'. This is not listed in package*.json: should it be?

**Comment by jgclark** [comment]
PR created, but despite it being on a issue21 branch I can't see it listed here: it's #52.

**Comment by dwertheimer** [comment]
Thanks @jgclark! I did have it in my package.json but not in my
package-lock, because NPM automatically upgraded my entire package-lock
file to “version 2” and I didn’t know what effect that would have on
others. But I committed it. So let’s see!
