### ISSUE TITLE
Plugin console.log output version info

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#213]
I think @mikeerickson  asked you to add a console.log at the start of a plugin run (like we used to have), e.g. "Plugin: XXXX running" or whatever. Can you pls pull the version number from the plugin.json and write that out to the console? e.g.  "Plugin: XXXX (v.0.9.0) running". It would help us on some of these user debugs like we were chasing this AM.

**Comment by jgclark** [comment]
@EduardMe I saw a tantalising glimpse of this in a console log posted by someone else, but I've not seen it in my own testing. Have you released this at all?

**Comment by dwertheimer** [comment]
May as well have it report the NotePlan version at the same time. :)

**Comment by jgclark** [comment]
@mikeerickson's improved logging functions (in dev.js) have it seems to be obviated the need for this.
So I'm closing it.
