### ISSUE TITLE
Add `version` to NotePlan `environment` object

### ISSUE THREAD

**Issue by mikeerickson** [NotePlan/plugins#219]
Would you please add the current running version of NotePlan to the `NotePlan.environment` object.  

Example

```js
const npVersion = NotePlan.editor.version  // 3.3.2 (734)
```

**Comment by dwertheimer** [comment]
Yes but Instead of NotePlan.editor.version, maybe NotePlan.app.version or just NotePlan.appVersion?

**Comment by dwertheimer** [comment]
@mikeerickson should this be part of "environment"?
Maybe that's what you meant by "editor" above?
`NotePlan.environment.appVersion` would be somewhat consistent with plugin.json

**Comment by dwertheimer** [comment]
or maybe just `NotePlan.appVersion` ?
