### ISSUE TITLE
Add new paragraph .type for 'horizontal line'

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#226]
Just a small point, but it seems to me that a horizontal line is a different type of paragraph type than all the others. As there's rather a profusion of ways of legitimately in Markdown making a horizontal line, I think it would be helpful to have a single getter and setter available that plugins can use.

I realised this when implementing a 'check for horizontal line' regex-based function some weeks ago. If I haven't already, I'll move it to helpers/paragraphs, as I want to use it in `/process offset dates` as well. But adding it to the full API would be better.

**Comment by dwertheimer** [comment]
I think @mikeerickson has written a RegEx for this in Templates2

But I agree having a type=separator would be very good

**Comment by jgclark** [comment]
FYI My regex is in helpers/paragraphs.js:
`export const RE_HORIZONTAL_LINE = `^ {0,3}((\\_\\h*){3,}|(\\*\\h*){3,}|(\\-\\h*){3,})$``
which attempts to match the CommonMark spec, not just NP's `---`.

**Comment by EduardMe** [comment]
NotePlan matches to more than "---", here's the full regex:

"(?:^|\\v)([\\-\\_]{3,}|\\*\\*\\* |(\\-(\\h|$)){3,}|\\*{5,})(?:$|\\v)"


But I do agree, there should be a type for this, so we don't need to go the
extra step or regex'ing it in JS.

**Comment by EduardMe** [comment]
Have added it, the type name will be `separator`

**Comment by jgclark** [comment]
Thank you. I will leave the issue open, to track my helper/* updates to use this.

**Comment by jgclark** [comment]
Helpers + my code updated. Closing.
