### ISSUE TITLE
getEventsForDay results are misleading on multi-day events

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#229]
Edge case scenario: a multi-day event starting part-way through day A and finishing part-way through day B.
getEventsForDay() called on day B returns the event (good) but with start time from day A (bad).

The code that needs changing is in NPCalendar.js around line 262.

**Comment by jgclark** [comment]
Perfect -- thanks so much for pointing me to this @dwertheimer. 

Now I look through the tests I see various other atomic functions that I could be using in place of some of my existing code.
Which further encourages me in my earlier suggestion that there are good things here to promote to one of the shared helper/ files.
Are you OK if I do some of that under this issue?

**Comment by dwertheimer** [comment]
Yes. Would be happy for you to move whatever functions you think could be
used by you and others.

**Comment by jgclark** [comment]
@dwertheimer I think I've found a bug in your `keepTodayPortionOnly`. It does a copy:
`  const eventCopy = { title: event.title, date: event.date, endDate: event.endDate, isAllDay: event.isAllDay } // event is immutable`
but there are other parts to the object which you're not copying, such as `.calendar`. This is leading to `undefined` strings appearing in the output.
Is there a way to copy the whole object, and then override the bits you want?

**Comment by dwertheimer** [comment]
@jgclark Nevermind, that's why I explicitly set the fields, because
spreading does not include any fields which are on the prototype (for some
reason, that's how objects come to us from Swift). So you will want to
explicitly set all the event fields like I did (partially).

**Comment by jgclark** [comment]
Thanks. Will release updates soon.
