### ISSUE TITLE
How to correctly do fetch() calls?

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#24]
One of the first things I wrote for NP plugin was the weather lookup using `await fetch()`. I remember it not proving easy to get working. This is what I landed up with:
```
const getWeatherURL = `https://api.openweathermap.org/...`
const jsonIn = await fetch(getWeatherURL)
if (jsonIn != null) {
  const weatherTodayAll = JSON.parse(jsonIn).daily['0']
  const maxTemp = weatherTodayAll.feels_like.day.toFixed(0)
...
} else {
  return `Sorry; unexpected data in Weather lookup`
}
```
Flow doesn't like this, saying `Cannot call `JSON.parse` with `jsonIn` bound to `text` because  `Response` [1] is incompatible with  string [2].`. Recently @nmn tidied up the code to deal with this, and split the first part up:
```
const response = await fetch(getURL)
const jsonIn = await response.json()
...
```
Flow likes this. However, this fails silently when running in NP.
The tutorial sites also like this, albeit suggesting more error handling, such as:
```
const response = await fetch(getURL)
  if (response.ok) { // if HTTP-status is 200-299
    let jsonIn = await response.json()
  } else {
    console.log(`Error ${response.status} in Weather lookup`)
  }
...
```
But when I try this, and variations on this, I can only ever get back `undefined` values for `response.*` values, despite the clear `await`.

So, I'm wondering if there's something about the execution environment that makes it go wrong?
Here's what appears to be a minimum not-working example:
```
async function testFetch() {
  const getURL = 'https://www.javascript.info/'
  const response = await fetch(getURL)
  console.log(response.status)
  console.log(response.statusText)
  if (response.ok) { // if HTTP-status is 200-299
    let textIn = await response.text()
    console.log(`Got ${textIn.length} bytes response.`)
  } else {
    console.log(`Error ${response.status} in fetch`)
  }
}
Could others please try this, and see if you can identify something I've missed? Thanks.

**Comment by nmn** [comment]
Does this work?
```
const jsonIn = await fetch(getURL).json()
```

It's hard to say exactly what's wrong, because `fetch` is function built into browsers. The exact code would depend on the API being contacted. There are servers that don't follow proper standard which probably why you're getting undefined.

**Comment by jgclark** [comment]
Thanks. Sadly that doesn't work, returning `TypeError: fetch(c).json is not a function. (In 'fetch(c).json()', 'fetch(c).json' is undefined)`.

**Comment by jgclark** [comment]
As there's no simple solution to this, I've instead worked out how to suppress this particular issue in Flow, and will add that to the single line in the two files concerned.
