### ISSUE TITLE
Improve logging for plugin errors

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#247]
In Discord conversation 15/3/2022 we settled on the following improvements:
- remove 'JSLog:' appearing in the NP log window
- *significantly* reduce the logging whenever opening the Plugin Preferences window
- emit at least line number when a plugin crashes, rather than nothing as at the moment
- flush to main log after every write from a plugin

@mikeerickson and @dwertheimer may elaborate further on this.

**Comment by EduardMe** [comment]
All except the first should be done by now. Added the first point just now,
so will be available in the next update.

**Comment by jgclark** [comment]
Not sure whether the line number is given on an error, but the rest seems done, so closing. Thanks, @EduardMe.
