### ISSUE TITLE
Fix CommandBar failing

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#248]
Anyway under this scenario:

> Running latest version of Summaries plugin's /saveSearchResultsInPeriod. Choose 'other week', 2022, 9, and then include just a single search term (e.g. #family, not #family, #friends). The command bar then pops up for less than 1/10 second before disappearing with a plugin crash.

David thinks it's probably a race condition:

> The crash here comes from a race condition where you are using CommandBar.onMainThread and onAsyncThread and trying to pop up a CommandBar to ask where you want things to be stored (probably) while the code is (still?) on the wrong thread. I commented out all the async/main thread stuff and the plugin works as expected.

As far as I can see I'm following the documentation at https://help.noteplan.co/article/70-javascript-plugin-api#commandbar.

But when David runs a (slightly different) set of tester code it's OK:
```
  await CommandBar.onAsyncThread()
  await CommandBar.showLoading(true, 'Loading', 0.1)
  await CommandBar.showLoading(false, 'Loading', 0.1)
  await CommandBar.onMainThread()
  await CommandBar.showOptions(['this'], '')
```

**Comment by dwertheimer** [comment]
Removing the showLoading calls in @jgclark’s code eliminates the crash. But those calls look to me totally in-line with the documentation.

**Comment by jgclark** [comment]
@EduardMe reports he's made a fix ready for next release.

**Comment by EduardMe** [comment]
We can review this in the next alpha. Let me just get to an alpha
releasable Meeting Notes feature state.

**Comment by jgclark** [comment]
Appears to be fixed on the original command that was having problems. Closing.
