### ISSUE TITLE
Add timeout to fetch() plugin calls

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#249]
After a long discord conversation today (16/3/22) this captures the need for timeouts on fetch() calls.
@mikeerickson requested the solution include `AbortController`.
https://dmitripavlutin.com/timeout-fetch-request/ was referenced.

**Comment by EduardMe** [comment]
Timeout added:

fetch("https://www.booking.com/hotel/mx/izla.en-gb.html", { "timeout": 1000
})
    .then(response => console.log(response))
    .catch(err => console.log(`Caught by .catch ${err}`));

**Comment by dwertheimer** [comment]
thanks @eduardme. That was fast!

**Comment by jgclark** [comment]
No issues reporting on this in a month, so closing.
