### ISSUE TITLE
np:qtn problems

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#255]
Running on b24 ...
1. With this `@Templates/Quick Notes/New Area Template` template
```
---
title: New Area Template
newNoteTitle: <%- prompt('?','Note name') %>
---
#area @review(<%# pickDateInterval({'question':'enter review interval'}) %>)
Aim: <%- aim() %>
Context: <%- context() %>
```
I'm getting this error:
```
**Template Error:** 1
 >> 1| #area @review(<%- await pickDateInterval({'question':'enter review interval'}) %>)
    2| Aim: <%- aim %>
    3| Context: <%- context %>
    4| 

Can't find variable: pickDateInterval
```

2. If I comment out the pickDateInterval() call, and then I get this different error:
```
# test name
**Template Error:** 2
    1| #area @review(<%# pickDateInterval({'question':'enter review interval'}) %>)
 >> 2| Aim: <%- aim %>
    3| Context: <%- context %>
    4| 

Can't find variable: aim
```
Note that the reported call with error is <%- aim %> whereas the template actually says <%- aim() %>.

3. When I try to use `np:insert` for this template, it doesn't find it (because it's in the sub-folder?). While it's good to have a folder to for qtn to use, I would expect that all templates should be available to np:insert etc.

**Comment by jgclark** [comment]
4. (An observation, not necessarily a problem.) Your example on how to define the title in a template frontmatter is
`newNoteTitle: <%- prompt('?','Note name') %>`
Running `np:migrate-quick-notes` I get the following instead:
`newNoteTitle: {{newProjectName}}`

**Comment by jgclark** [comment]
@mikeerickson they were very simple:
```
  quickNotes: [
          { 
            template: "New Project Template", 
            label: "Create a new Project note", 
            title: "{{newProjectName}}", 
            folder: "/"
          },
          { 
            template: "New Goal Tempalte", 
            label: "Create a new Goal note", 
            title: "{{newGoalName}}", 
            folder: "/"
          },
        ],
```

**Comment by dwertheimer** [comment]
@jgclark I'm confused by this `aim()` and `context()`. Are those functions that Templates should know about? I don't see it anywhere in the code.

**Comment by jgclark** [comment]
As they're not known functions they default to asking the user for a value. So I get text strings for Aim and Context in my project. Simples!
