### ISSUE TITLE
np:qtn not working as expected

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#257]
Further issues than #255 discovered after further improvements in b28, running against NP build 755.

**Context**:
All relate to template `@Templates\🗒 Quick Notes\Create a new Project note`:
```
---
title: Create a new Project note
type: template, quick-note, empty-note
newNoteTitle: <%- prompt('noteTitle', 'Project name') %>
folder: "/"
---
#project @start(<%- pickDate({'start':'Enter start date'}) %>) @due(<%- pickDate({'due':'Enter due date'}) %>) @review(<%- pickDateInterval({'review':'Enter review interval'}) %>)
Aim: <%- aim() %>
Context: <%- context() %>
Status:: 0@<%- date.now('YYYYMMDD') %>: project started
```
 
**Issues**:
1. This template doesn't show up in `np:qtn` list. Instead I only get
<img width="662" alt="Screenshot 2022-04-04 at 15 43 21" src="https://user-images.githubusercontent.com/1671754/161569053-61529b00-31ac-4467-b02e-34c69862c74b.png">

This is from the total set shown here:
<img width="769" alt="Screenshot 2022-04-04 at 15 44 23" src="https://user-images.githubusercontent.com/1671754/161569257-9931546b-dec4-40c1-ae9f-c995bab07e33.png">
I confirm all the ones in the "🗒 Quick Notes" folder have type: `quick-note`.

2. When I fire it using the `empty-note` menu or `np:` all the relevant questions get asked. But:
- the `pickDate(...)` questions get boiler plate question text "Please enter a date", not the question text I supply in the tag.
- the `pickDateInterval(...)` questions get boiler plate question text "Please enter a date interval", not the question text I supply in the tag.

NB: both the last two are using the old CommandBar input mechanism, not the newer native dialog which is what all the others use. IIRC this was my code originally; I can make updates if that would be easier.

**Comment by mikeerickson** [comment]
Fixed in 1.0.0-beta.29

**Comment by mikeerickson** [comment]
@jgclark I have made some adjustments in plugin, I used the following template for testing and all is working as expected now.

```
---
title: pickDate
---
#goal @start(<%- pickDate({'question':'enter start date'}) %>) @review(<%- pickDateInterval({'question':'enter review interval'}) %>)
Aim: <%- aim %>
Context: <%- context %>
```

**Comment by mikeerickson** [comment]
See the following video for demonstration, let me know if this does not align with your implementation

https://user-images.githubusercontent.com/183153/162077715-9cb268aa-1f74-4dd9-8b1f-b53931694f58.mp4

**Comment by jgclark** [comment]
As discussed on Discord, the prompt parameter still aren't being used.
Re-opening, so that's it clearer which code changes are related to the fix.

**Comment by mikeerickson** [comment]
@jgclark 

I have debugged this and I believe the error is in the actual template tags, not the processing.

In the existing helpers/userInput.js method the following is where the question is grabbed

```
  let { question } = (allSettings: any)
  question = question ? question : 'Please enter a date'
```

So, it is looking for the key question but in the template you supplied, it is set to start here `<%- pickDate({'start':'Enter start date'}) %>`

If I change this to `<%- pickDate({'question':'Enter start date'}) %>` to match the key defined in the userInput method, it works as expected

And, do the same thing for Due Date

If I change to this `<%- pickDate({'question':'Enter due date'}) %>` then I also see the expected "Enter due date" question in prompt

So, the revised template is
```
---
title: Create a new Project note (@jgclark)
type: template, quick-note, empty-note
newNoteTitle: "<%- prompt('noteTitle', 'Project name') %>"
folder: "/"
---
#project @start(<%- pickDate({'question':'Enter start date'}) %>) @due(<%- pickDate({'question':'Enter due date'}) %>) @review(<%- pickDateInterval({'review':'Enter review interval'}) %>)
Aim: <%- aim() %>
Context: <%- context() %>
Status:: 0@<%- date.now('YYYYMMDD') %>: project started
```

**Comment by mikeerickson** [comment]
https://user-images.githubusercontent.com/183153/162083669-9d56ec39-42f2-4289-8675-2e76107cebd9.mp4

**Comment by jgclark** [comment]
Thanks. Confirming it now works for me.
Closing issue, but will check documentation.
