### ISSUE TITLE
np:mtn not working as hoped

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#258]
b28 and NPb755

With this single note in the "🗓 Meeting Notes" folder:
```
---
title: Meeting Note Template
type: meeting-note, empty-note
newNoteTitle: <%- projectName() %> #meeting notes, <%- date8601() %>
folder: "/"
---
#### on ... at ...
With ...
Apologies ...
## Notes
...
```
I realise that the docs doesn't say `newNoteTitle` is supported, but I hoped it would still work.

When I use it via `np:mtn` I get these questions:
1. Enter projectName
2. What is date/time of meeting?
3. What would you like to discuss?

The latter two aren't in my template, but hey they make sense.

The resulting created note is:
```
# date-time
#### on ... at ...
With ...
Apologies ...
## Notes
...

```
which doesn't use the answers to Q1 or Q3, and puts the answer to Q2 as the title, which I don't want.

This might be more of an issue with the docs ... but it doesn't mention any of this.
Certainly it makes sense to me to re-use the `newNoteTitle:` frontmatter field in this setting too.

**Comment by mikeerickson** [comment]
@jgclark The extra questions are only for creating the new note title, which I can suppress if the template includes `newNoteTitle` field so that it works in the same fashion as `np:qtn`

Also, I will update the documentation accordingly to handle the existence of `newNoteTitle`

For completeness sake, would you mind sharing your "Meeting Note" template so I can see how it is constructed

**Comment by mikeerickson** [comment]
@jgclark In reading your template, I see you have `projectName()` which you are saying does not appear on your template.  When you want the prompt to appear, it should be:

1. A variable reference such as `<%- projectName %>`
2. A global or custom plugin method `<%- projectName() %>`
3. A prompt tag `<%- prompt('projectName','Enter Project Name') %>`

So in this case, I recommend using 1) or 3)

Please refer to this section for more information

https://nptemplating-docs.netlify.app/docs/templating-examples/prompt/

**Comment by jgclark** [comment]
> @jgclark In reading your template, I see you have `projectName()` which you are saying does not appear on your template.

I was saying the opposite. It was Q2 and Q3 I was commenting on.

**Comment by mikeerickson** [comment]
@jgclark I have completed the changes, with the following adjustments

1) If the template contains `newNoteTitle` it will be used when creating new note
2) If the template does not contain `newNoteTitle`, the user will be prompted to supply information
3) I have changed your desired `newNoteTitle` to the following
     a) Changed `<%- projectName() %>` to `<%- prompt('projectName','Enter Project Name:') %>`
     b) I have wrapped the whole `newNoteTitle` in double quotes due to use of `#` 
```
newNoteTitle: "<%- prompt('projectName','Enter Project Name:') %> #meeting notes, <%- date8601() %>"
```
4) I have updated documentation to reflect these changes
5) I have made Quick Notes and Meeting Notes dependent on new template format (frontmatter) as using with legacy template was going to be more difficult and figured now is a good time to break from legacy templates anyway

**Comment by jgclark** [comment]
Thanks, Mike, that all seems to check out. 
Good idea on point 5 to break with the past.
