### ISSUE TITLE
Fresh install of 3.4.1 does not install Templates plugin

### ISSUE THREAD

**Issue by reetu** [NotePlan/plugins#260]
**Describe the bug**
* When installing NotePlan 3.4.1 for the first time (via AppStore on Monterey 12.1), the Daily Journal Plugin does not work. 
* `nmn.Templates` plugin, which is a required dependency for Daily Journal Plugin, is not installed as expected.
* As a result, when I type `/dayStart` or `/todayStart` shortcuts into todays' note, no templates are loaded (because they are not configured). Instead it inserts the following text: 
```
<template was empty>
```

**To Reproduce**
1. Install NotePlan 3.4.1 (747) via AppStore on Monterey 12.1
2. Go to Preference > Plugins. The `Templates` plugin is not shown in the list. I cannot see how to enable/install the Templates plugin.
4. Download and enable the `Daily Journal` plugin
5. In todays' note, type `/dayStart`
6. `<template was empty>` is inserted into the daily note. 
7. See associated Plugin console logs below

**Expected behavior**
Templates plugin is shown in Plugins list and can be installed

**Screenshots**
List of available plugins; note Templates plugin is not available.
<img width="599" alt="Screen Shot 2022-04-13 at 3 22 39 PM" src="https://user-images.githubusercontent.com/1919274/163106571-da980a53-9d8a-41a6-b6a0-6bb15dc3eafd.png">
<img width="600" alt="Screen Shot 2022-04-13 at 3 22 47 PM" src="https://user-images.githubusercontent.com/1919274/163106579-65172b0e-ecaa-4692-89f6-aa51127afc6c.png">

**System**
 - Device: MacBook Pro 15 inch 2016
 - OS: macOS 12.1
 - NotePlan Version 3.4.1 (747)

**Additional context**

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin Console by going to `Noteplan > Help > Plugin Console`
1. Run the plugin you're reporting
1. Copy the output from the Plugin Console and paste it below
1. Delete any output that has personal information you don't want in there
```javascript
JSLog: Executing function 'dayStart'
JSLog: for '2022-04-13'
JSLog: getJournalSettings():
JSLog: 	dailyJournal settings from V2: {
  "reviewSectionHeading": "Journal",
  "templateTitle": "Daily Note Template",
  "moods": "🤩 Great,🙂 Good,😇 Blessed,🥱 Tired,😫 Stressed,😤 Frustrated,😔 Low,🥵 Sick,Other",
  "reviewQuestions": "@sleep(<int>)\n@work(<int>)\n@fruitveg(<int>)\nMood: <mood>\nGratitude: <string>\nGod was: <string>\nAlive: <string>\nNot Great: <string>\nLearn: <string>\nRemember: <string>"
}
JSLog: applyNamedTemplate: for template 'Daily Note Template'
JSLog: 	warning: template 'Daily Note Template' is null or empty
```

**Comment by mikeerickson** [comment]
@reetu Well, we are sort of at a crossroads here.  We have a new templating plugin about to be released (in the coming days) and it will supersede the current templating plugin.  

However, the new plugin will require the latest version of NotePlan v3.5, so this issue will be resolved in a few ways

- Upgrade to NotePlan 3.5
- Upgrade to Daily Journal Plugin
- Install new np.Templating plugin

I will leave this ticket open until np.Templating has been released, and the updated version of Daily Journals has been released (which will happen at the same time).  At that point, you will need to upgrade to NotePlan 3.5 to handle these upgrades.
