### ISSUE TITLE
Error in template plugin

### ISSUE THREAD

**Issue by mikeerickson** [NotePlan/plugins#27]
I am trying out the templates plugin (have tried with both) and am receiving the following error.  

I am using this with macOS 10.15.7 and had to adjust the `plugin.json` file to get it working with current relase version of NotePlan `3.0.23 (657)` so I am not sure if this is related to the os version.

I am willing to debug this further, but just wanted to bounce it off you all first.

![image](https://user-images.githubusercontent.com/183153/124398803-910e3a80-dccc-11eb-8282-54e254b3b1a9.png)

```
getOrMakeTemplateFolder
applyTemplate: found 3 options
getOrMakeTemplateFolder
parseFirstCodeblock: will parse format json5 length 1007
SyntaxError: JSON5: invalid character '\n' at 16:0
```

**Comment by jgclark** [comment]
Thanks for the report. Please could you attach a copy of your _configuration file here (blanking out any API keys first)?  (Not just copy and paste, but attach, as the mention of '\n' issue indicates an issue with line endings.)

**Comment by jgclark** [comment]
@mikeerickson I think I've worked out what's going on.
It turns out that even JSON5 -- designed to be "human readable JSON" -- can't handle multi-line strings. I can't tell which part of the configutation is failing for you, but try replacing linebreaks in strings with \n instead.
The default configuration section for dailyJournal did contain linebreaks rather than escaped linebreaks; last night I updated its defaults to use \n instead.

**Comment by dwertheimer** [comment]
Jonathan, feels like this may happen again. It's a natural thing to want to put in newlines. When someone puts a newline in a string in the config, e.g. "new\nline" it actually is escaped and looks like this "new\\nline", but when you type in an actual return, it shows up as a non-eescaped "\n",  We could scan for string opens and \n's that are not \\n's.  But, much easier in the short term to add a note in the template, which I just did (and pushed):

https://github.com/NotePlan/plugins/commit/3f09a4950bed70ddbcaf0fad1ea3de030ecf2b0c

Now says above the code fence:

IMPORTANT: The configuration code blocks below are validated in realtime by Noteplan as you edit.

If the configuration passes the validation, you will see configuration settings in color (e.g. orange,

green, purple, black, etc.). If there is a mistake in your configuration settings, the configuration

settings below will all be black. If you have a quoted "string" that you want to have a line break

in it, insert a " \n " where you want the line break, e.g. "This \n Is \n Threelines"

**Comment by jgclark** [comment]
Good work, @dwertheimer.
(I'd already added a note about this in lines 102-3, but yours is more extensive, so I'll remove mine.)
