### ISSUE TITLE
np.Templating Quick Note folder:<select>/<current> results in folder called <select>/<current> being created

### ISSUE THREAD

**Issue by vanteer** [NotePlan/plugins#270]
When creating a quick note (`type: quick-note`) using frontmatter configuration of either:

`folder: <select>`
or
`folder: <current>`

After prompting for the note name using the following:

`newNoteTitle: <%- prompt('noteTitle','Area') %>`

The note is created in a new directory called either `<select>` or `<current>` depending on what was in the frontmatter.

![image](https://user-images.githubusercontent.com/18755808/165279908-d0c68c39-83e2-405c-bb07-fa5f2c1f2580.png)

**Expected behaviour**
As per https://nptemplating-docs.netlify.app/docs/templating-commands/quick-notes

**System**
 - Device: Macbook
 - OS: macOS 12.3
 - NotePlan Version 3.5.1
 - np.Templating 1.0.2

**Plugin Console Log**
```javascript
JSLog: Executing function 'templateQuickNote'
```

**Comment by mikeerickson** [comment]
Fixed in np.Templating 1.2
