### ISSUE TITLE
Template variables

### ISSUE THREAD

**Issue by GregKaleka** [NotePlan/plugins#272]
(note this is the same request as #101, but for the new built-in templates)

My main use case for a template uses the same value in several places. As far as I'm aware, there's no way to have a single prompt populate several placeholders in the template. This would be a very helpful feature for me.

**Describe the solution you'd like**
If I provide the exact same placeholder text (such as `<%-GitHub Issue Number%>`) in several places, only one prompt should be provided, and all instances should be populated with the value entered.

**Comment by dwertheimer** [comment]
I am pretty sure that the templating plug-in that was just released by @mikeerickson a few hours ago will do what you want. One prompt sets the variable and you can use it multiple times. I don’t think that a variable can have spaces in it. But I’ve never tried

**Comment by GregKaleka** [comment]
Ooh ok yes, excellent. I figured out how to work it... one minor issue: variables don't work in the frontmatter section.

**Comment by dwertheimer** [comment]
yes, i found the same. @mikeerickson is going to work on that soon.
