### ISSUE TITLE
Add frontmatter support to API

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#284]
There was debate about this on [a Discord thread about something else](https://discord.com/channels/763107030223290449/978588087011643453/979127583155302400), but on balance we felt it would be good to add it. Lower priority though.

@mikeerickson pointed out we have his:
`const fmData = new FrontmatterModule().parse(template)`

but @dwertheimer countered "wouldn't `const fmData = note.frontmatter` make more sense?"

He and I would like to see some setters as well as getters. For example:
- `note.addOrUpdateFrontmatterField(key, value)`
- extend `newNoteWithContent(content: string, folder: string, filename: string): string` to add a `useFrontmatter: boolean` parameter

**Comment by dwertheimer** [comment]
Couple of thoughts:
Not sure we need the addOrUpdateFrontmatterField because frontmatter should just be an object that has properties and string values. So you just add to the object and set .frontmatter to it. Same as .content works. 
Also in your newNote... I suggest just passing the object of frontmatter as the param
Also I would suggest we have a .bodyContent field which returns just the non-frontmatter content or the whole note if there is none

**Comment by EduardMe** [comment]
We can extract the frontmatter through np.Templating's function. Just need
to see how easy that is and if the performance won't suffer. There might be
DataStore calls where we loop through a lot of notes and the frontmatter
has to be generated..., oh what if we just generate it when it's accessed!
I.E. the getter method gets called.

And what about setter? That could be muuuch trickier. I need the ranges of
the frontmatter attributes to be able to change them. I think that
functionality is missing in templating.

**Comment by jgclark** [comment]
@dwertheimer, I'm agnostic about the precise functions and calls, so happy to go with suggestions from you and others with more experience of modern data structures.

@EduardMe wrote:
> We can extract the frontmatter through np.Templating's function. Just need
to see how easy that is and if the performance won't suffer. There might be
DataStore calls where we loop through a lot of notes and the frontmatter
has to be generated..., oh what if we just generate it when it's accessed!
I.E. the getter method gets called.

Well, you could. But I was suggesting that this is an API call, not using Plugin code. I could write that myself. The reasons are as given in the discord thread, and for me its primarily about making frontmatter a properly supported part of the whole NP system.

> And what about setter? That could be muuuch trickier. I need the ranges of
the frontmatter attributes to be able to change them. I think that
functionality is missing in templating.

See above. Surely you only need to be deduce 1 item -- the paragraph that is the end of frontmatter? The start is by default paragraph 0.

**Comment by EduardMe** [comment]
That's what I mean, it's an API call, but internally it uses the Templating
code, so we don't have various slightly different implementations.

I'm relatively sure the setter will be more complicated than expected (more
moving parts than the getter). It's very blurry in my head right now.
Probably you want to do something like `Note.frontmatter.title = "different
title"`. Then we need to convert the frontmatter object into lines and
write it back at the right position, etc. or overwrite the whole block.
That's probably the simplest method. Here another complication is that the
frontmatter setter is not called directly...

**Comment by dwertheimer** [comment]
I wrote enough helpers in NPFrontMatter that I think we can close this ticket.
