### ISSUE TITLE
bug setting .filename

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#307]
Try as I might I can't get the new Note.filename setter to work properly. Whatever combination of folder path I append to the front of the filename, it renames to the root folder.

**Comment by jgclark** [comment]
Nudge. 
This is blocking a new release of NoteHelpers plugin.

**Comment by EduardMe** [comment]
Fix just released. Let me know if we can close it once tested.

**Comment by jgclark** [comment]
This now works with release 828. Though the open note in the Editor gets closed in the process.

**Comment by jgclark** [comment]
Thanks. If possible can you re-open to the same kind of window (main, split, float)?
