### ISSUE TITLE
Editing the search results line contents

### ISSUE THREAD

**Issue by LaurenaRehbein** [NotePlan/plugins#346]
**Is your feature request related to a problem? Please describe.**

I am using Noteplan 3 for project management and need to output a weekly status report for each of my almost 30 projects. 

Currently, I write a one-line status in each of the project notes and tag it with #client-status, then do a search for all lines with that tag. I then copy that and paste it into my report. 

However, each line in the search results is then followed by a display of the tags and the callback URL with brackets. I am then needing to remove each instance of the tags/callback for my report. 

***

Example result:

-  **Project status for project A:** This is a status line describing the results from this week. **#tag1 #tag2 ([[Project: Have a fun weekend]])**

What I need: 

-  **Project status for project A:** This is a status line describing the results from this week. 

*** 

**Describe the solution you'd like**

I would love to be able to override the search output to remove the tags and callback. 

***

**Describe alternatives you've considered**

I copied the plugin to a new directory and searched the code to try to comment out the parts that render the tags and callback but I haven't been able to figure it out!

Can possibly provide me some tips to edit the code to strip the syntax?

**Comment by dwertheimer** [comment]
I think we may be able to do this with a template when @mikeerickson releases Templating2.0. I envision a way to do things like this in Templates without having to write plugins. I think we could do this. So you would execute a search and then do a find/replace using templates. Question for you: are you using @jgclark's Search Extensions plugin to do the search or using NP built-in search. I wonder if Summaries could do this better. @jgclark thoughts?

**Comment by LaurenaRehbein** [comment]
@dwertheimer I am using @jgclark's Search Extensions plugin. I've not seen how Summaries can work, but Reviews plugin is not far off maybe.

**Comment by jgclark** [comment]
@LaurenaRehbein this is an elaboration of your #318.
I said then that Reviews plugin was very close with its existing `Progress:` field, and since then I've made it closer, partly with you in mind. But it's not released yet, as I'm waiting on Eduard to add some (imminent) new API features, and then me to test it all.
So I'm marking this as for me.

The next big release of Templating might well work for you as well, but that won't give you other Review-related functionality that you might want to use.

**Comment by jgclark** [comment]
@LaurenaRehbein here's some test output of my next release, which has some new settings and code which I hope will suit you.

```markdown
# #test Review List
Total: 4 active notes, **[Start reviewing 2 ready for review]**. _Last updated: 15/09/2022, 06:06:40_

_Key:  Project/Area Title	Progress_

### TEST (2 notes)
- [[Filer TEST destination]]	30% done: this is a text description of progress with date (4 days ago)
- [[Filer TEST source]]	done 0% of 1 tasks

### TEST/Other (2 notes)
- [[Project List Test 1]]	 84% done: progress line 3 is latest (2 wks ago)
- [[Project List Test 2]]	done 0% of 0 tasks
```

Where there's a line like `Progress: 30:2022-08-15: this is a text description of progress with date` in the project note, the most recent one is used in the list.  Where there isn't one of those, then a simple calculation of progress is used instead.
How does that look?

**Comment by dwertheimer** [comment]
@jgclark @LaurenaRehbein Is this solved? Can we close this ticket?

**Comment by jgclark** [comment]
Closing, as no response in many months.
