### ISSUE TITLE
Plugin Sweep Tasks doesn't run anymore

### ISSUE THREAD

**Issue by DHERRADOR** [NotePlan/plugins#357]
I usually execute every day the command /swt over my open tasks of the last day.
Since about 3 weeks more or less this command stop of work. It doesn't do anything at all.
I execute it. It asks the questions correctly, but at the end, when I choose "move" my tasks, it doesn't move anyone.

Please solve it. I loved it this plugin.

**Comment by dwertheimer** [comment]
I'm not sure when/if @nmn will revisit updating the sweep plugin. However in the meantime, maybe you can try the Task Automations plugin which has a command:
`/Review overdue tasks...` which does something similar but different in some ways.

**Comment by DHERRADOR** [comment]
Thanks dwertherimer.
But this automation is not a solution for my workflow.
I have a list of more than 40 open tasks, structured by groups with titles and subtitles.
I used /swt, because it maintained my structure of tasks ordered, only skipping the done tasks.
Please, could you revise the Sweeper plugin?

**Comment by dwertheimer** [comment]
Sorry to hear that. The problem is that a lot of NotePlan changed to make it more resilient (most notably that settings is now a settings panel and file rather than the brittle _configuration markdown document) etc. So Sweep needs to be at least partially re-written in order to work. Honestly, I'm not sure how it kept working for you until 3 weeks ago! @nmn had planned to re-write Sweep back in May but I think he got busy with his day job. I would suggest you describe your exact use case with some examples so that when he has a little time to look at Sweep again, he can make sure that it works for your use case.

**Comment by dwertheimer** [comment]
@DHERRADOR I am curious though...can you send your plugin log when you run Sweep? I ask because Sweep still runs for me.

**Comment by DHERRADOR** [comment]
Can you guide me how to send you that log?

**Comment by nmn** [comment]
@DHERRADOR can you tell me you exact workflow. Perhaps I can fix a subset of this plugin. 

My initial implementation just "moved" all overdue tasks to "today". But as more features got it added, it got complicated. So fixing it is a bigger job now and I barely have any time these days.

If you're willing to live with minimal functionality, I could probably make it happen next weekend.

**Comment by dwertheimer** [comment]
@DHERRADOR 
![Screen Cap 2022-11-07 at 15 56 46@2x](https://user-images.githubusercontent.com/8949588/200440796-f791d3d0-8c53-4d3c-8a94-7cf0d5b49cb2.png)
Turn logging on, run the /swt command, and copy/paste the Plugin Console results here

**Comment by DHERRADOR** [comment]
**This is what was saved in .log:**


onCloudUpdate - 13
CloudSync: 13 notes have changed
(sidebar) updating 13 notes
onUpdate
onUpdate
CloudSync: Saving 280 items.
NoteCache: Saving 127 general notes and 167 calendar notes.
DataStore (CloudSync): saveJSON - Saved data to cache 'currentNotesAppCache'.
DataStore (NoteCache): saveJSON - Saved data to cache 'notesAppCache'.
DataStore (NoteCache): archiveData - Saved data to cache 'calendarAppCache' of base 'caches'.
onUpdate
onUpdate
keyword:  on results: 0
keyword:  on results: 108
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
keyword: / on results: 108
Plugin 'np.Templating' is already downloaded, don't add it from the core plugins again
keyword: /s on results: 164
Plugin 'np.Templating' is already downloaded, don't add it from the core plugins again
keyword: /sw on results: 155
Plugin 'np.Templating' is already downloaded, don't add it from the core plugins again
onUpdate
keyword: /swt on results: 8
Plugin 'np.Templating' is already downloaded, don't add it from the core plugins again
onUpdate
[CMD] onSelect plugin
JSLog: Executing function 'sweepFile'
JSLog: Starting sweepFile on 20221108.txt
JSLog: Starting sweepNote for file: "20221108.txt" paragraphs:84 overdueOnly:false
JSLog: 	sweepNote: file:"20221108.txt" overdueOnly=false openTasks=61 overdueParagraphs:0 numTasksToMove=61
[CMD] Load options
commandFunc result: Optional([object Promise])
UI+URLScheme: parse incoming x-callback-url
Show restored window
UI+URLScheme: do something with openNote
UI+URLScheme: open note as x-callback
UI+URLScheme: note found (20221108.txt), ready to open it
open date 2022-11-07 23:00:00 +0000
open calendar note: 20221108.txt
saving scroll position 0.0 for 20221108.txt
Show context in sidebar for type: timeline
async open started

save note
note not updated
saveNoteIfNeeded - finished
loadExistingNote 20221108.txt - finished
Set content now for 20221108.txt
update version selection isconflict: false
loading scroll position 0.0) for 20221108.txt
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdate
onUpdate
FolderMonitor (BackupManager): presentedItemDidChange
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files
onUpdate
onUpdate
onUpdateAll
CloudSync: Loaded 127 from files
CloudSync: Loaded 0 from files

**And this was saved in plugin console:**

Executing function 'sweepFile'
Starting sweepFile on 20221108.txt
Starting sweepNote for file: "20221108.txt" paragraphs:84 overdueOnly:false
	sweepNote: file:"20221108.txt" overdueOnly=false openTasks=61 overdueParagraphs:0 numTasksToMove=61

**Comment by dwertheimer** [comment]
I will take a quick crack at this:
I found what appears to be a bug in the code (no idea why it ever worked
with this line), but let's try it:
pls use the /development-install command:
[image: Screen Cap 2022-11-09 at ***@***.***
search for sweep and load the latest sweep plugin
then try doing your sweep. let me know if this solves the problem. If not,
we'll have to wait for @nmn to be available.
Note: the reason sweep was hidden from the plugins is because people were
reporting data loss (similar to what you're seeing now, but you seem to
know how to get the content back), so just keep an eye out.
ᐧ

**Comment by DHERRADOR** [comment]
Many Thanks. It solved the problem.

**Comment by dwertheimer** [comment]
Glad to hear!
