### ISSUE TITLE
Add `weekStart` as week-note equivalent to `dayStart`

### ISSUE THREAD

**Issue by tastapod** [NotePlan/plugins#361]
I use `/dayStart` to lay out my day: diary overview, sections for Work, Personal tasks, etc. It would be great to have something similar for a week note.

Right now I seem to be using something like this:

```
## Things I have to do

## Things I have promised other people

## Things I want to do

## Coming up (tasks or events)
```

I'm pretty sure this will evolve, and it would be great to have a template to evolve it in!

**Comment by jgclark** [comment]
Added in v0.14.0
