### ISSUE TITLE
[Search Extensions] "Click to refresh" when appending to an existing note 

### ISSUE THREAD

**Issue by dvcrn** [NotePlan/plugins#364]
Love the "click to refresh" functionality, but currently it's only available for saved searches and not when appending to a note directly

I tried to play with the `search` command but it doesn't have an option to replace in a note (yet)

Some ideas:
- Insert a marker/boundary for this plugin to find existing inserted points
- Pass note name as parameter
- Search for that marker/boundary, replace when already exists

**Comment by EduardMe** [comment]
Thanks for this suggestion, can you elaborate on where "click to refresh" is? Do you refer to a plugin or to a feature in NotePlan?

**Comment by dvcrn** [comment]
Whoops I didn't realize the plugins are all in the same repository. 

This was for Search Extensions, I've added it to the title

**Comment by jgclark** [comment]
I will have a look at this, but I can't promise it quickly.

**Comment by jgclark** [comment]
Added in v1.2.1
