### ISSUE TITLE
/sweepFile Feature Request: Leave a note artifact when sweeping tasks with /sweepFile

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#4]
I find this plugin super useful. It would be good for there to be some user feedback (telling the user what's been done). I also think it would be good to leave a note at the top of the note you're sweeping FROM, something like:
[4 open tasks swept to 2020-05-22]

I would also recommend at some point to add a command like /forwardTodos that doesn't sweep them out, but forwards them, leaving a copy in place in the original file with a >2020-05-22 at the end.

Think about renaming "sweepFile", "moveTodos" to be more descriptive. sweepTodos might still be good for sweeping all files for todos. 

@nmn 
@jgclark @EduardMe If there's another place (e.g. Canny.io) I should put items like this, let me know. I just wanted @nmn to see it. :)

**Comment by EduardMe** [comment]
I think that’s a good place for feedback! I have added some minor changes
today (mostly dialogs and options improved) and released it. The recent
changes by @nmn have made it also far better to see what’s going on.

Maybe similar to how project notes are opened one by one, opening daily
notes and reporting what will be swept would help.

There is also a forward option in the latest version I think. You can
choose between moving and forwarding (copying).

**Comment by dwertheimer** [comment]
I love this user interaction. So cool. Nice job, @EduardMe.
However, in testing this out, I think I found a bug in Editor.removeParagraph
For instance, I put in 4 fake tasks and run the plugin. It does copy them all to my today note.
But it does not cleanly delete them all.
You will note from the pictures below, it deleted 2/3 of the lines, and removed just one letter from the line that remained!
I added some logging and the plugin seems to be correctly calling Editor.removeParagraph each time with the right item.

![Screen Shot 2021-05-22 at 10 52 05 PM](https://user-images.githubusercontent.com/8949588/119249956-b0ed0300-bb51-11eb-9bd0-7e1ec52583fd.jpg)
![Screen Shot 2021-05-22 at 10 51 48 PM](https://user-images.githubusercontent.com/8949588/119249958-b2b6c680-bb51-11eb-973e-6978ddc0d92c.jpg)
![Screen Shot 2021-05-22 at 10 51 35 PM](https://user-images.githubusercontent.com/8949588/119249959-b34f5d00-bb51-11eb-84d4-8d7bf7742f74.jpg)
![Screen Shot 2021-05-22 at 10 51 18 PM](https://user-images.githubusercontent.com/8949588/119249960-b3e7f380-bb51-11eb-9034-2f4002caccc2.jpg)

**Comment by nmn** [comment]
I wasn't able to reproduce the error you mention... Please see if you see the problem consistently, or maybe it was a one-off issue?

On the feature front, as you see, I've already added an option to "Reschedule" instead of "Move" tasks within Daily Notes.
Here are the rest of the features I envision:
- [ ] Choose custom Target date instead of Today. (Was mostly waiting for a calendar picker, but I can use Input for now)
- [ ] Ability to move tasks one at a time. (You'll get asked once for each note, and then you can choose to move or skip each task in that note)

Are there any other features you would want?

**Comment by dwertheimer** [comment]
That's so strange. I can reproduce it consistently on 2 different
computers, one running Big Sur, and one Catalina. Here's a screen record.

https://www.dropbox.com/s/yhq35xm4ux71cuu/npsweep.mov?dl=0

**Comment by nmn** [comment]
I'll check on this soon. In the meantime I suggest you try `Reschedule` instead.

**Comment by dwertheimer** [comment]
By the way I just tried it on the phone and it did the same thing.
@eduard, It’s so cool that the same plug-ins run on the phone. I was not
expecting that.

**Comment by jgclark** [comment]
@dwertheimer FYI the plugin architecture was significantly restricted in the early days to be just JavaScript, not other languages, specifically to allow plugins to run on iOS as well.

**Comment by nmn** [comment]
> @dwertheimer FYI the plugin architecture was significantly restricted in the early days to be just JavaScript, not other languages, specifically to allow plugins to run on iOS as well.

I don't see this ever changing. Apple hasn't allowed arbitrary code on iOS that's not JS forever now.

And we could allow some additional languages by providing tools to compile them to JS.

**Comment by EduardMe** [comment]
Jonathan also mentioned the removeParagraph issue today, I assume it's due
to the changing lineIndex. Will have a look at that.
