### ISSUE TITLE
Plugins pane does not allow you to expand the last item on the list

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#40]
See attached:
![flip](https://user-images.githubusercontent.com/8949588/128246378-e679d495-141d-4d29-9b61-95c324b12289.gif)

When you expand something above it (and it's expanded), you can then see it.

**Comment by EduardMe** [comment]
Thanks, I noticed this too. Checking why this happens…

**Comment by EduardMe** [comment]
Fixed it, will be available in the next beta/release.

**Comment by dwertheimer** [comment]
Thanks!
