### ISSUE TITLE
/ts(d) unexpected behaviour with repeated headings

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#405]
**Context**: I have lots of longish notes with many tasks covering some broad areas like "Car & Bike", "Finance", separated in a number of H3 sections, e.g. "Tax Return 2022". I generally want to keep enough history of when I've done things, in case I hit a problem later I need to refer back to.  So I move completed items to the "## Done" section, but under a similar H3 "Finance" etc. section.

**Describe the bug**: When I run /tsd from the H3 section with a mixture of open and completed tasks, I find all the completed tasks in the H2 Done > H3 section moved up into the H3 section with open tasks in.

**Expected behavior**: All items under the H2 Done section not to be changed let alone moved.

**Suggestion**: Add a simple call to `helpers/paragraph.js::findEndOfActivePartOfNote()` to only process items up to the H2 Done section.  I'm not trying this as a PR as I don't know the rest of this plugin's commands well enough to fiddle.

((In time I want smart auto-archiving down to the H2 Done section, but that's an issue for another time.)

**Comment by dwertheimer** [comment]
I will have a look this weekend. Thx for this and the other one. I will try to address them together.

**Comment by dwertheimer** [comment]
Done. Pls test. Thanks @jgclark
