### ISSUE TITLE
Reviews: Add enclosing folder setting

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#406]
I like that the plugin will keep all items together that are in a folder. that's great.
but I would like to put all my project folders together in an enclosing folder to keep them all together.
obviously I don't need to see that enclosing folder in the output.
so would suggest having a setting that says "hide top-level folder in output" or some such
thanks for considering!

**Comment by jgclark** [comment]
Will be released as part of v0.9.2
