### ISSUE TITLE
Smarter HTML Window re-use

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#420]
Scenario (illustrating something between Bug and Feature request):
1. Open an HTML window through some plugin command (e.g. Review list)
2. Move and re-size that window to suit.
3. Re-run the same plugin command.

**Current poor outcome**: HTML window competely re-starts, including going back to the initial position and dimensions.

**Better requested outcome**: where it can be determined that it's the same window purpose, re-use the existing window, not recreating the window from scratch.

Suggestion: this determination can now be done because we are about to have `customID`s set as part of the window creation call. I suggest where the customID and title is the same as in an existing window, just re-use it.

**Comment by jgclark** [comment]
A further related request: if its possible for NP to write to an existing HTML window without it stealing focus, then please expose a way to do this through the API.
So far I think the best way is to add to the HTML Writer a boolean parameter `updateInBackground`, which defaults to false.

**Comment by dwertheimer** [comment]
@EduardMe maybe we use this opportunity to change the signature so there are fewer params and just one options object so we can add things like this easily without worrying about having 10 params. We discussed this at the last meeting, probably in the notes somewhere.

**Comment by jgclark** [comment]
I think all this is now done.
