### ISSUE TITLE
Reviews: Ideas to speed up the Review 

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#442]
`/Project List` takes *a long* time to gather all the project files. It's painful any time I want to do it and actually discourages me from doing the reviews.

The speed problem is that it's looking in 100% of my notes (I understand why).

Some ideas (@jgclark you will have better ones):
1) It's fantastic that you can ignore certain folders and you can ignore the top most folder name in the output, but I'm wondering if maybe there should/could be a "Project Root" folder setting so that you could limit the scan to just that root folder (if set). I've organized it so my projects are all in a /Projects folder. That may or may not be the best way/place to put them, but it's working for now. Looking just in this folder would help me.
2) What makes the scan slow is that it has to look in the content of each document looking for hashtags. But `DataStore` itself is not slow (it's cached). So maybe another setting could be a "Project Note Titles Must Contain" setting, and if set, it only looks in notes that have a word (e.g. "Project") in the title. That way, you could filter DataStore down to just those files before scanning contents.

Thoughts?

**Comment by dwertheimer** [comment]
@jgclark Thinking more about idea #1, if I as a user say that my projects are always in a "Projects/*" folder, then it would not just need to be one Projects folder at the root but could be:
ClientA/Projects/FooProject
ClientB/Future/Something/Projects/BarProject
etc.
Would still be way faster

**Comment by jgclark** [comment]
I agree its slow, and slower than expected given the caching of hashtags. I certainly found an issue with `.hashtags` being stale, so perhaps I switched to do a full search? Next week I'll try to do some instrumenting to see where the most time goes.

And what about this option instead?
3. New setting with 'Folder(s) to find Project notes', to suit the wider case (that includes myself) where I have several top-level folders with Projects in. This would take any sub-folders too.  The existing 'Folders to Ignore' setting would still apply and could defeat any sub-folders if necessary.

**Comment by dwertheimer** [comment]
Also, can I ask that the new folder include filter does not just filter for root level folders but for any folder in the path that matches the include?

See my note here:
https://github.com/NotePlan/plugins/issues/442#issuecomment-1530741870

**Comment by dwertheimer** [comment]
@jgclark I edited the code a little above, so pls look at the version on Github (not email)

**Comment by jgclark** [comment]
Many thanks for all this. I will try and make a new release tomorrow.
J

**Comment by jgclark** [comment]
Done, thanks.
Though the findNotesMatchingHashtag() function hadn't actually been "reading the entire DataStore for each hashtag" AFAICT. So the saving might not be as much as you expect.
I've changed the Include setting to be 'includes' not 'startsWith' for you.

**Comment by dwertheimer** [comment]
Closing this issue with PR: https://github.com/NotePlan/plugins/pull/444
