### ISSUE TITLE
Reviews: Rich/HTML project links should open by filename instead of title

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#447]
![Screen Cap 2023-05-09 at 21 49 35@2x](https://github.com/NotePlan/plugins/assets/8949588/c0c1199a-4d2f-4f20-ac52-9b4066eb3612)

Clicking an "open by title" link opens the first document that has that title, but there could be several with that same name (as in my example above), and you may not get the document you expect. Better to use openByFilename:

```
noteplan://x-callback-url/openNote?filename=XXXX 
```
instead of:
```
noteplan://x-callback-url/openNote?noteTitle=YYY
```

Some discussion [here](https://discord.com/channels/763107030223290449/1105544160968200274/1105718474841542677):

**Comment by dwertheimer** [comment]
May be possible to do this way:

@jgclark#5203 it actually may be a one line change:
```js
        const noteOpenActionURL = createOpenOrDeleteNoteCallbackUrl(this.title, "title", "", "splitView", false)
```
to:
```js
        const noteOpenActionURL = createOpenOrDeleteNoteCallbackUrl(this.note.filename, "filename", "", "splitView", false)
```

**Comment by jgclark** [comment]
I've done this ... but in case there might be other aspects of this I've not considered, I'm leaving open for now.

**Comment by dwertheimer** [comment]
Thanks @jgclark
