### ISSUE TITLE
/Move Note: add a new folder

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#448]
Awhile back, I added the ability to (optionally) allow the user to create a new folder in the `chooseFolder` dialog.

```js
function chooseFolder(msg: string, includeArchive: boolean, includeNewFolderOption: boolean, startFolder: string): string
```
Will you please use this option in the `/move note` command?
Just set the 3rd param to true.

While you're at it, you may want to do a quick scan of other places you use `chooseFolder` to see if there are other places you may want to add it (maybe in Filer/newNote?).

**Comment by jgclark** [comment]
It's now updated, and will soon be released in v0.17.
