### ISSUE TITLE
np.Preview - onEditorWillSave -> refresh preview

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#449]
I want to be able to edit my mermaid diagram and see the result of the edits in the preview. Would be ideal if we could have an onEditorWillSave trigger that refreshes the preview now that you have all this great code for keeping the window in the right place/size. :)

**Comment by jgclark** [comment]
I knew you'd ask for this! 
Q: what do you want the wait interval to be before the update is triggered? I.E. at most every N seconds?

**Comment by dwertheimer** [comment]
I am not sure we need the limit since Eduard is already debouncing before this trigger is called. Worth trying without.

**Comment by jgclark** [comment]
Released a beta to @dwertheimer yesterday

**Comment by dwertheimer** [comment]
Sorry I didn’t get a chance to test!
