### ISSUE TITLE
aaronpoweruser.ReadwiseUnofficial: Pagination of Export API is ignored

### ISSUE THREAD

**Issue by TobiasMende** [NotePlan/plugins#452]
**Describe the bug**
I realized that this plugin does not import all my readwise highlights. Looking a bit into the code and the Readwise API, the reason seems to be that the API does not return all books at once but might paginate and return a `nextPageCursor` in that case.

**Expected behavior**
If `nextPageCursor` is present in the response, repeatedly call the API to get all books.

I really like this plugin! — I will be happy to provide a PR adding this behavior if nobody else is already working on this.

**Comment by TobiasMende** [comment]
@aaronpoweruser Thank you for contributing this plugin. It has helped me a lot to keep Readwise in sync with Noteplan.

Is my understanding of this limitation correct? Happy to try a contribution, if nobody else is working on it. :-)

**Comment by dwertheimer** [comment]
@TobiasMende Thank you for the offer. Let's see what @aaronpoweruser says, but speaking for @jgclark and myself, we'd love to have you contributing to the NotePlan plugin dev community, whether on this plugin or something else (including some great feature you may dream up).

**Comment by aaronpoweruser** [comment]
I'll take a look. My highlight database isn't large enough to need to be paginated. So I may need some help testing.

**Comment by aaronpoweruser** [comment]
@TobiasMende  Can you please verify the fix.

**Comment by TobiasMende** [comment]
@aaronpoweruser Thank you! I just checked it out and tried it locally. Seems to work pretty well for my. 😊🎉🙏

**Comment by WillPlatnick** [comment]
@dwertheimer @jgclark @aaronpoweruser What is the process for releasing version 1.0.1 from 7 months ago? I can only download 1.0.0 in NotePlan.

**Comment by jgclark** [comment]
I released 1.0.1 yesterday, so I'm now closing this issue.
