### ISSUE TITLE
np.Preview live preview metadata - 2 things

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#455]
1. there should be a command that will insert the live preview metadata in frontmatter and pop up a preview
2. the title should probably not have a "#" in front of it

<img width="539" alt="Screen Cap 2023-06-25 at 17 55 46@2x" src="https://github.com/NotePlan/plugins/assets/8949588/320c7b01-79e6-4e94-b2ec-97f324e4fd3b">

**Comment by jgclark** [comment]
> 1. there should be a command that will insert the live preview metadata in frontmatter and pop up a preview

Sorry; I don't understand. Do you want a separate command that shows frontmatter in some way, and one that ignores it? At the moment I'm doing a simple job of doing 1.

> 2. the title should probably not have a "#" in front of it

True.

**Comment by dwertheimer** [comment]
Maybe I just missed it, but I did not see a command that inserts the live-reload frontmatter into the source document. I read the Readme and it told me what the magical incantation was and so I had to hand enter it. Is there a command which converts a document to a live-previewing document (for normal users who don't know how to hand-enter frontmatter)? If so, I missed it.

**Comment by jgclark** [comment]
You didn't miss the command @dwertheimer, but I'm now adding it for you. Hardest thing is to know what name to give the command. What do you think about "/start live preview"?

**Comment by jgclark** [comment]
@dwertheimer ready to test in (committed but unreleased) v0.4.0
