### ISSUE TITLE
Please Add Support for Relative Dates and Headings in Quick add to Calendar Notes in the Quick Capture Plugin

### ISSUE THREAD

**Issue by laestrella26** [NotePlan/plugins#464]
**Is your feature request related to a problem? Please describe.**
I want to use Siri on my Apple Watch and HomePods to add tasks/notes to NotePlan via Apple Reminders and Shortcuts. However, without relative date support combined with the ability to add my task to a particular heading in the callback URL, I can't create a cool shortcut that lets me position data based on the Reminders list name. Instead, I find myself manually picking the daily note + the heading every time which is not as convenient for many of my tasks/notes. It still creates too much friction.   

**Describe the solution you'd like**
I think it'd be a significant improvement if the callback URL **(/quick add to calendar note)** would allow me to (i) **choose use relative dates for notes** and (ii) **organize tasks/notes under specific headings**. This adjustment would streamline my workflow and make adding tasks/notes via Siri much more efficient.

Alternatively, you can also update **/quick add task under heading** and **/quick add line under heading** to add relative dates  since both of those already have the heading feature. 

**Describe alternatives you've considered**
I have been using the "add a note to today's journal" function and manually setting the plugin to place my notes under my most commonly used heading. However, this workaround still requires additional time to reposition what i dictated, making it a less-than-ideal solution.

**Additional context**
This all ties in with the automation of Apple Shortcuts, which I use a lot. I set my shortcut to run automatically when I open NotePlan. Adding relative date support and specific heading selection to the calendar note callback URL in Quick Capture  would really help me and people like me who lean heavily on Siri, Shortcuts or maybe even other tools like Drafts to keep to help supplement some of the features that the core NotePlan experience is missing.

**Comment by jgclark** [comment]
@laestrella26 Release Candidate is ready for testing -- see Discord.

**Comment by jgclark** [comment]
Delivered in v0.14.
