### ISSUE TITLE
Dashboard: User-Editable Header/Footer Sections

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#469]
Once XCallback links are clickable on the dashboard, I'd love to be able to create some evergreen links and text in the preferences that will be displayed as a header or footer section. I would use this to have quick access to my frequently used commands (xcallbacks) and links to frequently used documents.

I would suggest that you run the contents of these preference fields through the np.Templating parser so that we could use Templating to adjust them to our liking (e.g. calculate today's date or tomorrow's note or something)

**Comment by jgclark** [comment]
I'll need a bit more convincing that this idea best lives in the Dashboard. There are other third-party utilties, as well as Stream Decks and the like, that are specifically about keeping sets of commonly used things instantly available.  Do you have anything in mind that can't in theory be achieved by x-callback calls?

**Comment by jgclark** [comment]
Closing as no update.
