### ISSUE TITLE
Dashboard: Bring to Front param

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#470]
As mentioned in [Discord](https://discord.com/channels/@me/863719873175093259/1136694828328026212)

I would like, when I click this link, for the dashboard to always come to the top. I find that most of the time, Dashboard is behind my NP window and I have to go to the Window menu and scroll down to get it to come to the forefront. Is there a way? If not, can we add a param to bring it to front? I'd like to have a keyboard shortcut also.

**Comment by jgclark** [comment]
At the moment the plugin dev can decided whether to ask `showHTMLV2()` to focus or not.
Currently Dashboard just says 'not'.
I think it would be good to make it 'notUnlessNotCurrentlyOpen', to do what you suggest @dwertheimer .
But before I do that, I think it's worth deciding whether to make this the default behaviour if the named window isn't already open.
What do you think?

**Comment by dwertheimer** [comment]
@jgclark For the way I use Dashboard (may or may not be universal), what would work for me:
- trigger always keeps note in the background
- any other type of invocation (command bar or xcallback) brings to front

**Comment by jgclark** [comment]
I like that scheme.
I can't immediately see a way of making that default behaviour simply by the showHTMLV2 helper. But it's trivial to make it happen from a trigger.
In which case I'll continue to have focusing as the default behaviour for the helper, but update the trigger.
It will come in the v0.6.0 release.
