### ISSUE TITLE
Dashboard: Hide scheduled items

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#471]
I always write todos in my daily note, and I generally schedule them for some day in the future.
Once an item is scheduled and it's not scheduled for today, I don't think it should clutter my dashboard. 
For instance, here's a task I wrote today and immediately scheduled it. I don't want to see it in today's dashboard anymore, because for now at least, it's taken care of.

<img width="315" alt="Screen Cap 2023-08-07 at 13 29 00@2x" src="https://github.com/NotePlan/plugins/assets/8949588/af8e560b-867d-48e1-aa5f-e63cb383d376">

**Comment by jgclark** [comment]
Good idea, and already implemented. At least if you're using the existing 'scheduled' paragraph type. Any reason you're not using this?

**Comment by jgclark** [comment]
@dwertheimer by the look of it, I added this in v0.6.2, but forgot to note it.
Please could you check it's doing what you wanted?

**Comment by dwertheimer** [comment]
Thank you @jgclark
