### ISSUE TITLE
Create a way to have a keyboard shortcut for the calendar note views in NotePlan: Monthly, Quarterly, Yearly, etc. 

### ISSUE THREAD

**Issue by danieldanilov** [NotePlan/plugins#475]
NotePlan currently provides keyboard shortcuts for some views: e.g. today, tomorrow, yesterday, and this week. 

However, there is no way to quickly navigate to "this month", "this quarter", or "this year" and similarly "next month", "next quarter", "next year", and even potentially "last month", "last quarter", "last year".

The only way to do that is either to navigate by clicking, or by looking up the specific month/quarter/year in the command bar. 

This is a problem for users who choose to use only specific views. For example, using only Daily, Monthly, and Quarterly means that I cannot easily navigate to 2/3 of the views I use consistently. 

It's worth noting that it's also not possible to write "this month", "this quarter", "this year" etc. in the command bar either. The specific month/quarter/year itself must be typed out (although, for the "Year" part, this is less of an issue, because you just type out the 4 digits and it's usually the first result).

A solution I'd love to see is have these options become menu items that users can manually assign keyboard shortcuts for. This could be part of a plugin, but eventually, I think it should be part of the core product.

[I originally asked about this in Discord](https://discord.com/channels/763107030223290449/767038050739027988/1139984602275008562)

Thank you!

**Comment by jgclark** [comment]
I will pick this up, but you also want to press for Eduard to add it into the main app.

**Comment by dwertheimer** [comment]
> A solution I'd love to see is have these options become menu items that users can manually assign keyboard shortcuts for. This could be part of a plugin, but eventually, I think it should be part of the core product.

@danieldanilov Agreed that @EduardMe should add these to the app as menu items. In the meantime, you could just do this with keyboard shortcuts and x-callbacks. 

noteplan://x-callback-url/openNote?noteDate=today&timeframe=month
noteplan://x-callback-url/openNote?noteDate=today&timeframe=quarter
noteplan://x-callback-url/openNote?noteDate=today&timeframe=year

See details:
https://help.noteplan.co/article/49-x-callback-url-scheme#opennote

**Comment by danieldanilov** [comment]
> In the meantime, you could just do this with keyboard shortcuts and x-callbacks. 
> noteplan://x-callback-url/openNote?noteDate=today&timeframe=month 
> noteplan://x-callback-url/openNote?noteDate=today&timeframe=quarter 
> noteplan://x-callback-url/openNote?noteDate=today&timeframe=year

Ah, great, thank you! I tried to find a way to link to them, but could not find the generic way to open the current month/quarter/year. Thank you for that! I'll use them for now in my workflows.

**Comment by EduardMe** [comment]
Thanks for the idea, have noted it!

**Comment by jgclark** [comment]
OK, I've added new commands to NoteHelpers plugin:
"Show This Month" (alias /stm)
"Show This Quarter" (alias /stq)
"Show This Year" (alias /sty)
which can have keyboard shortcuts, though the aliases are very easy.
To be released soon.
