### ISSUE TITLE
[Quick Capture v0.4.5] /int command cannot find Inbox note

### ISSUE THREAD

**Issue by AngeloStavrow** [NotePlan/plugins#48]
**Describe the bug**
The `/int` command cannot find any note named "📥 Inbox" in the root-level directory of notes, and therefore creates a new note with every invocation.

**To Reproduce**
1. Invoke the quick-add to inbox command by opening the Command bar (<kbd>Command</kbd>+<kbd>J</kbd> in NotePlan), typing `/int`, and pressing <kbd>Return</kbd>.
2. The plugin presents a message in the Command bar ("") and prompts to choose a folder for the creation of an Inbox note.
3. This happens every time the `/int` command is invoked, creating a new note named "📥  Inbox" every time.

**Expected behavior**
I believe that I should should be prompted to enter a task and it will be added to the existing Inbox note, but I can't be sure — this has never worked for me.

**Screenshots**
<img width="939" alt="Screen Shot 2021-08-13 at 07 22 12" src="https://user-images.githubusercontent.com/387655/129350259-1864d7fc-3c2c-4167-8b22-69510bfee220.png">

**System**
 - Device: Mac
 - OS: macOS 11.5.1
 - NotePlan Version 3.0.23 (637)
 - Plugin Name & Version "Quick Capture" v0.4.5

**Comment by jgclark** [comment]
Thanks for the report. I can't reproduce, but then I'm on NP v3.0.26 (647). Please join the Discord if you haven't already, and look on the releases channel to find links to the betas.
Also, please can you list the 'inbox' section from your `📋 Templates/_configuration` file?

**Comment by AngeloStavrow** [comment]
Sure thing! Here's the relevant bit from the config file (I didn't change anything from the default):

```javascript
inbox: {
    inboxFilename: "📥 Inbox.md",
    inboxTitle: "📥 Inbox",
    addInboxPosition: "prepend",
},
```

I don't see any updates on the Mac App Store, so I guess I'm stuck on NP v3.0.23 (637) for now.

**Comment by dwertheimer** [comment]
Angelo, can you pls check your today 's calendar note and see if the plugin is inadvertently putting the note there?

Also, can you pls send @jgclark the output from Noteplan > Help > Plugin Console (when you run the command)?  Thanks!

**Comment by dwertheimer** [comment]
Thanks Angelo.
@jgclark I can reproduce.

Sending you a video in Discord

**Comment by AngeloStavrow** [comment]
@dwertheimer, thanks for looking at this! It wasn't putting in my calendar note, it was prompting me to create a new "📥 Inbox" note each time I attempted the command.

**Comment by dwertheimer** [comment]
Yep. We know what the issue is. Thanks for the report. @jgclark will be
fixing when he gets back in town.

**Comment by jgclark** [comment]
@AngeloStavrow please try now with new v0.5.0 release.

**Comment by AngeloStavrow** [comment]
Works like a charm! Thanks for the quick fix, friends. ❤️
