### ISSUE TITLE
Gather dead-end references

### ISSUE THREAD

**Issue by tf13** [NotePlan/plugins#480]
I'd like to be able to see the `[[wikilinks]]` go to notes that don't yet exist. (e.g., somewhere I link to `[[Project X]]` but there is as yet not note with that name.)

At its simplest, I could run a command and get a list of all such links, either in a new note or in some interactive page/panel (linked search). Tapping one link would create that note, and then in the new note, in the references section, I could see all the places I used the same wikilink.

Reasoning: I often link names, concepts or other topics as I write; if no such note exists, I create a placeholder. (I do this especially for people.) Usually while writing I don't have time to create the note (easy, just tap) or add anything to it; but later, when I might have time, I have no way of identifying which notes need curation. 

Alternative: perhaps a search or filter could already give me a list of notes containing such links, letting me tap on one and create the new note?

@dwertheimer suggested this could be a good fit for TidyUp

**Comment by jgclark** [comment]
This was released recently as v0.9.0 of Tidy Up plugin.
