### ISSUE TITLE
Quick Capture Plugin: Callback URL fails when selecting calendar note from command bar

### ISSUE THREAD

**Issue by laestrella26** [NotePlan/plugins#481]
**UPDATE 8/27** - I just realized that this isn't happening because of a calendar note it's happening with the first item in the list of the command bar. It just so happened that the first item was the calendar note.

**Describe the bug**

Using the call back URL to add a line under a heading without specifying the note in arg0 and selecting a calendar note from the command bar, does not work. Selecting a regular project note works as expected. The issue appears to be specifically with the relative notes like "today" or "this week" note. This is probably an issue with some of the other callback URLs as well.

**To Reproduce**
1. Go to 'Quick Capture Plugin'
2. Use the call back URL without specifying the note
3. Choose a calendar note (fyi, the daily note is not labeled "today" in the command bar)
4. See error: nothing happens, the command bar goes away and the note isn't populated with the information. the console is showing that the plugin couldn't get the note

**Expected behavior**
The line should be added under the heading, regardless of whether the daily or regular project note is selected.

**System**
 - Device: iPhone14 Pro, MacBook Air
 - OS: iOS 17 beta 5, macOS Sonoma beta
 - NotePlan Version: 3.9.6 (1077)
 - Plugin Name & Version: Quick Capture Plugin v0.14.0

**Additional context**
The issue seems to be specifically related to the calendar notes if you try to select it from the command bar.

**Plugin Console Log**
Executing function 'addTextToNoteHeading'
```
2023-08-22 12:06:36 | DEBUG | jgclark.QuickCapture v0.14.0 :: starting /qalh with arg0 'null' arg1 'Inbox' arg2 <text defined>
2023-08-22 12:06:36 | WARN  | getNoteFromParamOrUser :: Couldn't find note with title 'null'. Will prompt user instead.
2023-08-22 12:06:36 | DEBUG | folders / filteredFolderList :: Starting to filter the 39 DataStore.folders with inclusions [] exclusions []
2023-08-22 12:06:41 | ERROR | getNoteFromParamOrUser :: Couldn't get note
```

**Comment by jgclark** [comment]
Thanks. Have fixed and will release shortly as 0.14.1.
