### ISSUE TITLE
Tidy Up: Move root notes does not find empty notes

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#482]
You may or may not consider this a bug. When I go to clean up the root level notes, I want to move everything that is out there, including empty notes that were made by mistake. There is a "delete note" option in the option list, so it would be perfect. The problem is that it seems to only find notes that have titles, and so I am left with empty notes at the root level.
In this example, one note has some content, but no title. Two others are totally empty. But Tidy Up/Root Notes doesn't find them.

<img width="821" alt="Screen Cap 2023-08-23 at 09 50 05@2x" src="https://github.com/NotePlan/plugins/assets/8949588/1970f45f-8bcf-410f-8851-142da7573dc0">

```
2023-08-23 09:48:55 | ERROR | fileRootNotes :: Failed to get note for some reason
2023-08-23 09:48:55 | ERROR | fileRootNotes :: Failed to get note for some reason
2023-08-23 09:48:55 | ERROR | fileRootNotes :: Failed to get note for some reason
2023-08-23 09:48:55 | DEBUG | fileRootNotes :: 0 notes moved from the root folder
```
If the plugin is issuing an ERROR, then I assume this is not intentional. 

I don't think having a title should be required.

```js
      if (n && n.title && n.title !== undefined) {
```

**Comment by jgclark** [comment]
First is a bug, and is fixed in 0.8.1.
Second: no idea now how there were two, but I'd already removed the second one ...
