### ISSUE TITLE
Custom themes: Hide square brackets

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#483]
how would you feel about hiding the square brackets on links in the Condensed themes?

<img width="445" alt="Screen Cap 2023-08-23 at 11 27 03@2x" src="https://github.com/NotePlan/plugins/assets/8949588/98934d19-6b7a-412a-baac-11f9df3844b1">

**Comment by dwertheimer** [comment]
Apple Spark has at least the wiki link square brackets hidden:
<img width="504" alt="Screen Cap 2023-08-23 at 11 29 43@2x" src="https://github.com/NotePlan/plugins/assets/8949588/d42b1ac3-a5de-4d53-b37a-0b872518e72f">

That's better, but I personally would like to hide the brackets on both types if possible. Thoughts?

**Comment by jgclark** [comment]
I don't feel strongly. 
BTW do you mean just my themes (in a different repo)?

**Comment by dwertheimer** [comment]
Yes. Specifically, I use all the condensed JGC themes and I’m really trying
to avoid forking them because it’s really hard to keep everything straight.

**Comment by jgclark** [comment]
Done. I've gone further than Apple Spark themes and hidden the brackets in the second part `(↗︎)` as well.

**Comment by dwertheimer** [comment]
Thx @jgclark!
