### ISSUE TITLE
How to deal with a YAMLException?

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#490]
I've found an edge case with `NPFrontMatter::ensureFrontmatter()` helper. It fails raising a YAMLException on the following:
```
---
title: Health🌀
meta: @review(1m) @reviewed(2022-03-14)
---
```

This is technically correct, as I discover via https://yamllint.com/ that there's a prohibition on @ character starting a value. This won't get in the way of Project+Reviews plugin which uses `@review(2m)` and which some will include (with or without a key) in frontmatter.  I found the issue when trying to add a trigger to a note which already had this frontmatter, via a command that does use the helpers.

We could say "well, the standard's the standard so let this continue to be a rare error". But it took me a while to work out what was going on, and I have access to the code. If someone else hits it we're going to go through this debugging again.  So I think I'd prefer to find a workaround that allows this slight anomalous use. After all, we're not trying to use full-on YAML here, but just simple key:value pairs.

The workaround I have in mind is to change the temporarily treat any leading `@` in a value as `\@`, which is allowed.  But this means changing `@templating/support/modules/FrontmatterModule/getAttributes` and probably more, which I mustn't do unilaterally.

Thoughts @mikeerickson  @dwertheimer ?

**Comment by dwertheimer** [comment]
@jgclark as an aside, as discussed previously, it would be great if Projects/Reviews could read straight frontmatter (in addition to working as per this post):
```
---
review: 1m
reviewed: 2022-03-14
---
```

**Comment by jgclark** [comment]
> I wrote this function which I use every time I write the frontmatter.

Excellent.

> [EDIT] BTW, perhaps at some point`getAttributes` should be moved to the @helpers file at the same time, but for now, the easiest thing to do would be to sanitize at the top of `getAttributes()` function in np.Templating

@mikeerickson are you OK with these 2 suggestions?

And in Discord DM David and I agreed (I think) that we should treat `... #something` in a YAML value as a hashtag that gets protected, but treat `... # something` (with space) as the start of a comment that gets ignored (as per the YAML standard).

@mikeerickson are you OK with this as well?

**Comment by dwertheimer** [comment]
@mikeerickson looking forward to hearing your thoughts.

@jgclark I just pushed up the changes. A lot more code than I bargained for, but I think I have captured most of the edges and am protecting users from accidentally messing up frontmatter YAML 

Every one of @mikeerickson's tests are passing, as well as my old and new tests in NPFrontMatter and the rest of the repo.  Deals with all these edges:

<img width="671" alt="Screen Cap 2023-09-15 at 09 48 48@2x" src="https://github.com/NotePlan/plugins/assets/8949588/3f0b1ac9-6a27-4b11-9a3d-a7fa6cf7ae97">

I have moved getAttributes and getBody to NPFrontMatter and have refactored the calls to those in the whole repo. I have rebuilt Templating and all appears fine.

@jgclark Pls rebuild and test:
- [ ] DailyJournal
- [ ] Meeting Notes

Let me know what you find.

**Comment by jgclark** [comment]
I first looked at **NoteHelpers**, as that's the one that contains "/add trigger".
It's now working for the edge cases here, thanks.
However, I wasn't expecting the side effect of permanently adding the surrounding quotes. I was suggesting temporarily treating the offending characters as quoted, so that the processing can work, but _not_ changing the text in the note.

**Comment by dwertheimer** [comment]
@jgclark Thanks for testing. Ah. Well this is in fact the old code doing this, not the new code. It's always been sanitizing on write. You're just seeing it now because now I'm now allowing it to read before it does the write (it was previously crashing on the read before the write). So I can turn off the sanitizing on write, which will allow people to write whatever they want in frontmatter, including things which may break the `fm()` parser. We will be somewhat shielded because we will sanitize non-standard YAML on read (as long as we use the `getAttributes()` function. What I don't know though is how @EduardMe is parsing frontmatter on his end and whether non-standard YAML will keep his triggers and title reading from working properly. I can turn it off and we can test what happens.

**Comment by jgclark** [comment]
> @jgclark Thanks for testing. Ah. Well this is in fact the old code doing this, not the new code. It's always been sanitizing on write. You're just seeing it now because now I'm now allowing it to read before it does the write (it was previously crashing on the read before the write). 

Aha.

> So I can turn off the sanitizing on write, which will allow people to write whatever they want in frontmatter, including things which may break the `fm()` parser. We will be somewhat shielded because we will sanitize non-standard YAML on read (as long as we use the `getAttributes()` function. 

Good: that's what I think I'm after. I will need to start using `getAttributes()` in Reviews plugin, particularly when we extend it to use YAML fields.

> What I don't know though is how @EduardMe is parsing frontmatter on his end and whether non-standard YAML will keep his triggers and title reading from working properly. I can turn it off and we can test what happens.

I suspect he's not trying to use YAML yet, but just treating the H1 line as a special case.

So, if I understand correctly:

- [ ] DW tweak helpers
- [ ] JGC update NoteHelpers
- [ ] JGC update DailyJournal

I've looked in the past at the Meeting Note code, and failed to fully understand what's going on, so I don't want to change that.

**Comment by jgclark** [comment]
I've released a rebuild of NoteHelpers, but having checked there should be no way we hit this edge case from DailyJournal. So I'm leaving that alone until it next needs releasing for other reasons.
