### ISSUE TITLE
CSS conversion failures

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#492]
@jgclark You may need to put some defensive code/fallbacks for when the calculations/conversions fail. Right now, I am getting some CSS that looks like this:

![Screen Cap 2023-10-18 at 16 39 40@2x](https://github.com/NotePlan/plugins/assets/8949588/6555b0ba-32ca-49d1-9763-72ade48718ef)

**Comment by jgclark** [comment]
I had defensively coded here, but I didn't include a !isNaN check.
I've changed NPThemeToCSS line 88 from
```js
    baseFontSize = Number(DataStore.preference('fontSize')) ?? 14
```
 to be:
```js
    const fsPref = DataStore.preference('fontSize')
    baseFontSize = (fsPref && !isNaN(Number(fsPref))) ? Number(fsPref) : 14
```
but I can't test it as I can't unset the NP preference. Please test.

**Comment by dwertheimer** [comment]
This seems to have fixed it. Thanks @jgclark
