### ISSUE TITLE
Preview: Live refresh steals focus

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#495]
---
title: Diagram
triggers: onEditorWillSave => np.Preview.updatePreview
---
I have a mermaid diagram. As I make changes in the MD file with the trigger, the preview changes. AWESOME! Thx @jgclark 
The problem is that every time it saves, the preview steals focus and my typing then is ignored.
I would like the preview window to *not* be focused in the live-update scenario.

**Comment by jgclark** [comment]
Fixed in 0.4.3
