### ISSUE TITLE
Dashboard: Use Ignore Folders (for overdues)

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#496]
@jgclark Thank you for adding Overdues. Unfortunately it's picking up a lot of test content for me in folders I usually ignore. 

I don't know if you'd be ok using the "ignore folders" setting you already have there for something else. That would work for me.

<img width="548" alt="Screen Cap 2023-11-17 at 22 25 25@2x" src="https://github.com/NotePlan/plugins/assets/8949588/6b1564af-c4f8-45d2-91c1-b94793b0598f">

**Comment by jgclark** [comment]
Added in 0.7.1.
