### ISSUE TITLE
Quick Capture Plugin - Callback URL for Quick Add Task Under Heading not adding text as markdown task

### ISSUE THREAD

**Issue by laestrella26** [NotePlan/plugins#499]
**Describe the bug**
When I use the callback url for quick add task under heading: _noteplan://x-callback-url/runPlugin?pluginID=jgclark.QuickCapture&command=quick%20add%20task%20under%20heading_

**WITHOUT** arg0 and arg1  then my text doesn't get added with a markdown checkbox. The plain text just gets added.

**To Reproduce**
Create a shortcut with the callback url and run it.

**Expected behavior**
My url encoded text has a leading - [ ]

**Screenshots**

**System**
 - Device: iPhone 15
 - OS: iOS 17
 - NotePlan Version: 3.9.11
 - Plugin Name & Version [e.g. "Templates" v0.2]

**Additional context**

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin's Preferences by going to `NotePlan's menu > Preferences > Plugins` and clicking the settings "cog" icon next to the plugin in question. Scroll to the bottom and set the logging level to "DEBUG" and click "Save & Close"
3. Now open the Plugin Console by going to `Noteplan > Help > Plugin Console`
4. Run the plugin command you're reporting
5. Copy the output from the Plugin Console and paste it below
6. Delete any output that has personal information you don't want in there
```javascript
    PASTE_PLUGIN_CONSOLE_OUTPUT_HERE
```

**Comment by jgclark** [comment]
Please specify the actual URL you're using, rather than just the first part. I need to see how you aren't specifying arg0 and arg1.

**Comment by jgclark** [comment]
That example works for me when selecting today's note, and "bottom of note", or other existing headings.
But I see that it doesn't work properly when selecting "top of note". 
Is that what you're experiencing?

**Comment by laestrella26** [comment]
Yes, that's correct. I can confirm that the issue with the markdown checkbox not being added occurs when I select "Top of Note" in NotePlan.

**Comment by jgclark** [comment]
Thanks for confirming. I will get that fixed.

**Comment by jgclark** [comment]
Fixed in 0.15.2
