### ISSUE TITLE
iOS: Plugins do not show up in Command Bar until app is force quit

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#5]
Upgraded iOS app. It says on AppStore page and inside app that there are plugins.
Go to command bar and type / - nothing comes up
Cloudkit sync is otherwise working perfectly - all notes are there
After Force-quit Noteplan on iOS and re-launch: Plugins are there

**Comment by jgclark** [comment]
Closing this, as it must at worst have been a short-lived problem.
