### ISSUE TITLE
Note Helpers Plugin - Create Index File - structure the headers based on folder nesting

### ISSUE THREAD

**Issue by ariccb** [NotePlan/plugins#504]
**Is your feature request related to a problem? Please describe.**
For the Note Helpers Plugin,
The output of the index file is hard to glance through, with the folders titles being appended with /folder/nested/folder it's hard to find the one you need.
**Describe the solution you'd like**

Right now the plugin command for creating an index note is great, but it's outputting each folder and it's nested folders as `## Root Folder/Nested Folder 1/Nested Folder2`. 
The result is (note the ## H2 Headings)
```
## Root Folder
- file in root
- file in root

## Root Folder/Nested Folder 1
- file in Nested Folder 1 
- file in Nested Folder 1 

## Root Folder/Nested Folder 1/Nested Folder 2 
- file in Nested Folder 2
- file in Nested Folder 2
```
It would be super awesome if instead of the `/`, you output it like this (note the different heading levels for each deeper Nested Folder)
```## Root Folder
- file in root
- file in root

### Nested Folder 1
- file in Nested Folder 1 
- file in Nested Folder 1 

#### Nested Folder 2
- file in Nested Folder 2
- file in Nested Folder 2
```

This would make it really easy to use the CMD+/ command to fold/unfold each folder level, and also would be visually easier to quickly scan to which folder you're looking for. The `## Root Folder/Nested Folder 1/Nested Folder 2 ` format makes it really hard to get a high level understanding of the folder structure

**Additional Context**
https://discord.com/channels/763107030223290449/1117945664500924437/1186433200675897397

**Comment by dwertheimer** [comment]
What if (optionally?) instead of using headings for folders, it just used bold text and indented items along the way so that the result is a tree-like structure that represents the actual structure? This would reduce the amount of repeated clutter in the folder titles

**Comment by jgclark** [comment]
Completed in v0.19.0
