### ISSUE TITLE
Dashboard + Projects&Reviews: Override current theme for styling

### ISSUE THREAD

**Issue by antony-sklyar** [NotePlan/plugins#506]
**Is your feature request related to a problem? Please describe.**
I have setup a cutom theme for myself that works perfectly for my needs by breaks "Dashboard" and "Projects & Reviews" html views.

**Describe the solution you'd like**
I would like to be able to set another theme in plugin settings that the plugin would use to display its html view. For example, let it use "Toothbleach Condensed" fonts and colours instead of the fonts and colours from my custom theme.

**Describe alternatives you've considered**
You could also spend some time to support proper styling for monospaced fonts, but IMO this would require more effort than just use one of the default themes that the plugin already supports.

**Comment by jgclark** [comment]
Will do.

- [ ] Dashboard
- [ ] Projects & Reviews

**Comment by jgclark** [comment]
Will be released soon.
