### ISSUE TITLE
Quick Capture Plugin - NotePlan is prompting for "text to add" with Callback URL even though I'm sharing that text via the callback URL

### ISSUE THREAD

**Issue by laestrella26** [NotePlan/plugins#507]
**Describe the bug**
I'm using the callback url to add a line under heading/task under heading in the Drafts app, which worked previously to pass text that I've typed in Drafts to NotePlan and then leaving the remaining arguments empty so that NotePlan can prompt me for the specific note and heading. However, NotePlan asks me for the "text to add" even though I'm passing it along. I also have the same result using Apple Shortcuts. I've ensured that the text is URL encoded.

noteplan://x-callback-url/runPlugin?pluginID=jgclark.QuickCapture&command=quick%20add%20task%20under%20heading&arg2=[[draft]]

noteplan://x-callback-url/runPlugin?pluginID=jgclark.QuickCapture&command=quick%20add%20line%20under%20heading&arg2=[[draft]]

**To Reproduce**
1. Use Drafts or Apple Shortcuts or however you would invoke the callback url
2. Use the above callback url and leave all the arguments empty except for arg2 which allows you pass on the relevant text

**Expected behavior**
I expect the app to only ask me for the relevant note and the heading where i want to put the task or the line.

**Plugin Console Log**
```javascript
   Executing function 'addTaskToNoteHeading'
2024-01-05 14:08:52 | DEBUG | jgclark.QuickCapture v0.15.2 :: starting /qath with arg0 'Testing 123' arg1 '' arg2 <text defined>
2024-01-05 14:08:52 | DEBUG | folders / filteredFolderList :: Starting to filter the 44 DataStore.folders with inclusions [] exclusions []

```

**Comment by jgclark** [comment]
Eduard has changed something in the callback handling very recently (3.9.11?). I think this is probably responsible for things now not working for you.
The documentation currently says "where an argument isn't valid (empty in the table below), don't include it", but it looks now that's not true. I've tested with passing empty arguments, but that's not fully working either: I think I need to update my logic as well.

**Comment by laestrella26** [comment]
Thanks, for the update. Hopefully, there is a solution to this. It's one of my favorite things about NotePlan.

**Comment by jgclark** [comment]
I've spent some time on this plugin again.
I confirm that empty arguments now need to be passed in callbacks.
Your first example above therefore needs to become:
`noteplan://x-callback-url/runPlugin?pluginID=jgclark.QuickCapture&command=quick%20add%20task%20under%20heading&arg0=&arg1=&arg2=draft`
Note that it ends `=draft` not `=[[draft]]` which I didn't spot before, as the brackets get hidden in the theme.

Please test this to see if that works for you.

**Comment by laestrella26** [comment]
Woo hoo! That worked. I tested both adding tasks under heading and line under heading in Drafts using the url.  

I can't tell you how much I have missed this feature. THANK YOU!!!!

**Comment by jgclark** [comment]
I'm closing this now that NP 3.10 is out of beta. I've updated the documentation to say that args are still needed even if they're empty.
