### ISSUE TITLE
Callback Link Not Working (Habits & Summaries)

### ISSUE THREAD

**Issue by CraneRewind** [NotePlan/plugins#508]
**Describe the bug**

Habits and Summaries plugin.  After using `/appendProgressUpdate` to create a summary in a note (monthly note, with mtd for me), clicking on the Refresh link does nothing.

The only way for my to update the tracker is to type `/appendProgressUpdate` again.

**To Reproduce**
1. Insert a habit tracker summary somewhere - for me, I use the 'mtd' setting and 'current' and initially insert it into my January note.
2. Make a change that should be picked up by the tracker, e.g., add another item to the things you count/measure.
3. In the summary, click on the 🔄Refresh link.

**Expected behavior**
I expect the summary to be updated.  If the Plugin Console log is open, I expect to see some activity in there.

**Actual behaviour**
Nothing happens when I click refresh.

**Screenshots**
1. Initial setup showing versions (3.9.11 (1143) of Noteplan, v0.20.2 of plugin).  Plugin console open.
2. Showing that plugin is in debug mode for logging.
3. Video showing nothing happening when I click the refresh link, but stuff happens when I type `/appendProgressUpdate`.
4. Removing trailing ')' from link to show the exact callback.

**System**
 - Device: Mac
 - OS: macOS14.0 (23A344)
 - NotePlan Version: 3.9.11
 - Plugin Name & Version: Habits and Summaries v0.20.2

**Additional context**
I don't often use callbacks.  I was using the habits plugin several months ago without issues.  I took it back up again this week and noticed that the link didn't work.  I didn't really think anything of it until I tried a second plugin, where the links really do make things easier to use.

**Plugin Console Log**
I am not including the log, because nothing happens when I click on the refresh link itself.  You can see that in the video.

**Attachments**

![1 Setup - console open, versions](https://github.com/NotePlan/plugins/assets/98125767/9b3b3978-247b-48ab-9486-0db19d5feda9)
![2 Plugin set to debug](https://github.com/NotePlan/plugins/assets/98125767/7d17ed6d-5112-45f5-bf79-72a98350d4a8)

https://github.com/NotePlan/plugins/assets/98125767/dcc15e28-75e6-4402-bc12-622750b547e4

![4 Showing refresh link](https://github.com/NotePlan/plugins/assets/98125767/eb53fc10-c9f7-467b-9e16-e77d9e36797b)

**Comment by jgclark** [comment]
Excellent problem report, thanks.
I can't reproduce this at the moment, as I get the refresh kicking off in the logs. However, the next stage is broken, and I think it relates to a change in callback handling that Eduard introduced in 3.9.11.  I will need to check and probably update my logic too.
