### ISSUE TITLE
Note Helpers: bug in calendar notes detection when renaming note filenames to match note titles

### ISSUE THREAD

**Issue by antony-sklyar** [NotePlan/plugins#510]
**Describe the bug**
When I am using `/rename inconsistent note filenames` command I get alerts that it cannot rename calendar notes, even though it should not rename them at all, because I select the root folder of the project notes, and because it does not show any calendar notes as those needing to be renamed.

**To Reproduce**
Possible cause of the bug might be the fact that I am using dates in `yyyy-mm-dd` form as parts of my meeting notes titles, as you can see on the screenshot.

I would also like to mention that none of my notes gets renamed, it just shows this error "This command does not support renaming calendar notes" multiple times.

**Expected behavior**
I would expect it to rename each note properly. And even if it encounters some error in one of the notes, it should proceed with non-problematic notes sucessfully.

**Screenshots**
![CleanShot 2024-01-07 at 08 00 58@2x](https://github.com/NotePlan/plugins/assets/24554007/8b619501-2dae-491f-a36d-56097aad752d)
![CleanShot 2024-01-07 at 08 11 05@2x](https://github.com/NotePlan/plugins/assets/24554007/6f31cac4-2866-4a82-899b-2ecdb818eda2)

**System**
 - Device: MacBook Pro
 - OS: Sonoma 14.2.1
 - NotePlan Version 3.9.11 (1143)
 - Plugin Name & Version "Note Helpers" 0.18.2

**Plugin Console Log**
```javascript
Executing function 'renameInconsistentNames'
2024-01-07 08:17:03 | DEBUG | helpers/userInput :: chooseFolder folder:/ value:/ keyModifiers: keyModifiers.indexOf('opt')=-1
2024-01-07 08:17:03 | DEBUG | helpers/userInput :: chooseFolder folder chosen: "/"
2024-01-07 08:17:03 | DEBUG | jgclark.NoteHelpers v0.18.2 :: renameInconsistentNames(): Chosen folder: /
```

**Comment by jgclark** [comment]
Thanks for the report.

**Comment by jgclark** [comment]
Fixed spurious alerts, and made it a bit more forgiving.
Will release as 0.19.1 soon.
