### ISSUE TITLE
Dashboard: Option to >reschedule but not move tasks + Heading

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#516]
I tend to like to keep a record of when I came up with a todo (esp when that todo lives in a project note). Sometimes tasks in my calendar note are surrounded by context. So I tend to change the >dueDate on a task where it was rather than moving that task to a new note. Dashboard obviously moves tasks from a previous note to today by default. I would like to make 2 requests:

- [x] Allow for user to specify a heading name in tasks to move tasks underneath so that they don't just end up at the top of today's note. For example, the top two tasks were moved by dashboard. I would like them to be moved under "Tasks" if I am going to move them.

<img width="394" alt="Screen Cap 2024-01-14 at 12 43 13@2x" src="https://github.com/NotePlan/plugins/assets/8949588/8a096f7b-bd63-4494-bb62-3c0c294ec27a">

- [x] I would like an option to have tasks rescheduled where they were rather than moved to today's note. I suppose you could do that with a cmd+click or something but having the default work in the way that the user likes to work is probably a good idea.

Thoughts?

**Comment by jgclark** [comment]
As it's you, and as you've asked so nicely, I will add 😁.

**Comment by dwertheimer** [comment]
That's very nice. Thank you @jgclark !

**Comment by jgclark** [comment]
The first is already done, and will be included in v0.8.3.

**Comment by jgclark** [comment]
Both are done, and I pushed changes yesterday for you to test.
