### ISSUE TITLE
Feature Request: RepeatExtensions allow generation for last x days

### ISSUE THREAD

**Issue by ameritrash** [NotePlan/plugins#525]
Currently, to have the repeat extensions generate the repeated task, I need to remember to run it on each day that contains a completed extended repeat task, or I need to remember to place the onEditorWillSave trigger.

This feature request is to run allow "/generate repeats" to have a number of days to look back on. for example, "/generate repeats -1w" would generate repeats for all the days of the last week (using the same time syntax as the extended repeats).

Note: having an automatic daily note template where I have inserted this trigger would eliminate the need for this request, as the trigger would be the already and allow the functionality I'm looking for. unfortunately, this is not quite possible yet, and I'm really worried about accidentally abandoning a task that I felt was important enough to make repeating. so this is a solution to minimize this risk.

**Comment by jgclark** [comment]
v0.14.0 of Tidy Plugin now gives you this capability: either as "/Generate @repeats in recent notes" or through a template tag.
I'm going to mark this as closed, but do open it again if you find any issues.
