### ISSUE TITLE
Repeat function no longer works (after update to beta version 3.10 (1159))

### ISSUE THREAD

**Issue by Der-Canonier** [NotePlan/plugins#527]
**Describe the bug**
Previously, the repeat function always worked perfectly (apart from the fact that it did not work from the reference and the dashboard), but since the last beta update to version 3.10 (1159), no new task has been created.

 I also installed version 3.10 (1158) (because it still worked until then), but it no longer works with that either.

**Screenshots**
The Trigger
![image](https://github.com/NotePlan/plugins/assets/15310331/ab1b964e-3c5c-4980-907b-34a6041a19bd)

Task before completing
![2024-02-09_15-55-10](https://github.com/NotePlan/plugins/assets/15310331/0cb3e637-658d-45fe-8f66-1b489151fdb7)

Task after completing. A new task on 16.02.2024 is not created
![2024-02-09_15-57-05](https://github.com/NotePlan/plugins/assets/15310331/86148c41-70d0-4e6b-a729-6c5138cd1fc7)

**System**
 - Device: MacBook, iPhone 15 Pro, iPad 12.9 Pro
 - OS: iOS 17.3.1, macOS 14.3
 - NotePlan Beta Version 3.10 (1159)
 - Plugin Name & Version 🔁 Repeat Extension plugin 0.6.1

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin's Preferences by going to `NotePlan's menu > Preferences > Plugins` and clicking the settings "cog" icon next to the plugin in question. Scroll to the bottom and set the logging level to "DEBUG" and click "Save & Close"
3. Now open the Plugin Console by going to `Noteplan > Help > Plugin Console`
4. Run the plugin command you're reporting
5. Copy the output from the Plugin Console and paste it below
6. Delete any output that has personal information you don't want in there
```javascript
    PASTE_PLUGIN_CONSOLE_OUTPUT_HERE
```

I'm not sure if I'm using the Plugin Console correctly.
It is set to "Debug" and I have clicked on save.
Do I still have to execute a command?

![2024-02-09_16-30-59](https://github.com/NotePlan/plugins/assets/15310331/5d9dd2c2-33a0-4572-81ad-7a7474503b4f)

![2024-02-09_16-34-33](https://github.com/NotePlan/plugins/assets/15310331/548ab38d-fffc-4eac-90cc-d310fb21736b)

**Comment by jgclark** [comment]
Yes, as it says, you need to open the console before you run the command.
From your screenshot I can't tell if the `triggers:` line is inside a frontmatter block or not.

**Comment by Der-Canonier** [comment]
Unfortunately, this is the only thing that is written into the plugin console (as shown in the screenshot).

If I end the task and a new one should actually be created, nothing is written to the console.

Is this now better to see on the screenshot?

![2024-02-09_18-40-44](https://github.com/NotePlan/plugins/assets/15310331/613473db-aad0-4993-9d97-f3c91b7ca939)

As already written, I have not changed anything and so far everything has worked perfectly

**Comment by jgclark** [comment]
OK, thanks. I can reproduce this. I can still run /rpt to get the repeats made, but it now won't happen automatically.

Assigning @EduardMe as this looks to be a wider failure of the trigger, not the plugin.

**Comment by EduardMe** [comment]
@jgclark It's related to onEditorWillSave not being triggered, which we just figured out over at Discord. Next beta should fix it! Uploading soon.

**Comment by Der-Canonier** [comment]
I'm looking forward to it 😊

**Comment by jgclark** [comment]
Eduard has fixed the problem with triggers in the latest NotePlan beta, so I'm closing this.
