### ISSUE TITLE
Further Event Helpers improvements

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#53]
Further improvements:
- add 'notes' and 'URL' field as template options, now that the API supports this.

But, @EduardMe, can you not include the 'location' field as well?

**Comment by EduardMe** [comment]
@jgclark  Technically yes, I left it out for now, because it’s a bit more complicated. In the UI the user selects an option from a dropdown box while typing (it looks up the location data). But it allows also for a custom location. I could add the location as a custom field.

**Comment by jgclark** [comment]
As a first step if you could make add a getter for it, then it could be included in the Event Helpers lists. I agree that setting its value via an API is more complicated.
