### ISSUE TITLE
Dashboard: add new items under heading preference/setting

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#539]
Dashboard has buttons that allow you to add new tasks/checklists to today's note. Today, that puts the new items at the top of your note"

<img width="388" alt="Screen Cap 2024-03-06 at 16 56 51@2x" src="https://github.com/NotePlan/plugins/assets/8949588/7be984de-fa4e-4493-8b09-f6a295496c17">

I would like to request that there be a setting in Dashboard prefs for the title/heading to put the tasks under. If that field is blank, it does what it does today. If that field has a string in it, the tasks are placed underneath a title of that name.

In my case above, I would put the string "Tasks" in the setting, so that new items would always be placed under "Tasks" which is a heading in my daily note template.

**Comment by jgclark** [comment]
Implemented in 1.0.0-a5.
