### ISSUE TITLE
Editor and HTMLViews unavailable in onSettingsUpdated() calls

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#545]
**Checks**
- [x] I confirm I have restarted NotePlan and this problem still persists.
- [x] Is this a repeatable problem?

**Describe the bug**
`Editor` and `HTMLViews` are unavailable in onSettingsUpdated() calls.
This function defined by each Plugin is automatically when its setting sheet is updated. This is very helpful. But in my more complex plugins, I want to immediately run a refresh (e.g. Dashboard or Project Lists). These touch Editor and or HTMLViews, and thus fail.

**What do you expect it to do instead?**
Even when the settings sheet still has focus, I want open Editor and HTMLViews to be addressable.

**System**
This has been happening without fail for at least 6 months (and was previously reported on Discord), and so has existed over many releases and several OS versions.

**Comment by jgclark** [comment]
@EduardMe this is probably my most annoying issue. Is there a chance you could please at least look and see if this is a small or a big challenge?

**Comment by jgclark** [comment]
Ping to @EduardMe

**Comment by EduardMe** [comment]
Is this when you change a setting from the preferences pane? I added the last known editor reference there, not sure if it works. I think it's easiest if you try it with the next alpha / beta update.

**Comment by jgclark** [comment]
Thanks. I've now tested this on 2 plugins, and it's working. Thanks for sorting this.
