### ISSUE TITLE
m1well.Expenses plugin doesn't work

### ISSUE THREAD

**Issue by AnnapaolaC** [NotePlan/plugins#547]
I installed the plugin, even manually, moving and renaming the files but the script does not work.

**Comment by dwertheimer** [comment]
I see that the plugin was not available anymore from the Plugins panel. Not sure why. But I re-published it so it is. Works for me when I install and run it:

If I run this command:
![Screen Cap 2024-03-27 at 17 48 54@2x](https://github.com/NotePlan/plugins/assets/8949588/f40b292c-c18f-4565-94d5-0fe47c4fa51e)
It asks me for some data which it then stores in the "finances" folder:
![Screen Cap 2024-03-27 at 17 49 49@2x](https://github.com/NotePlan/plugins/assets/8949588/1cd7b9a3-5576-48b1-b415-70bf4ea467f2)
Which looks like this:
# 2024 Expenses Tracking
2024-03-27	122	Education	122.00

**Comment by AnnapaolaC** [comment]
I installed version 1.7.2 and after the screen where it makes me choose the type of tracking (individual, shortcut and fixed) nothing happens, and it doesn't create the note in the folder.

**Comment by dwertheimer** [comment]
Which of the options did you try? Individual, shortcut or fixed?

Is there anything in the plugin console when you run it?

**Comment by AnnapaolaC** [comment]
I have tried all the options.
How do I see the plugin console?

**Comment by jgclark** [comment]
Help > Plugin console

**Comment by AnnapaolaC** [comment]
I have tried all the options.
By entering the option "individual" the plugin console gives this message:

Executing function 'expensesTracking'
2024-04-01 16:35:17 | DEBUG | loaded config from settings: :: {
  "fixedExpenses": [
    "{\"amount\":670,\"active\":true,\"month\":0,\"category\":\"Living\",\"text\":\"Flat Rent\"}",
    "{\"amount\":399,\"active\":true,\"month\":1,\"category\":\"Insurances\",\"text\":\"Car Insurance\"}",
    "{\"amount\":9.99,\"active\":false,\"month\":0,\"category\":\"Media\",\"text\":\"Spotify\"}"
  ],
  "categories": [
    "Viaggio",
    "Alloggio",
    "Vitto"
  ],
  "columnOrder": [
    "date",
    "category",
    "text",
    "amount"
  ],
  "dateFormat": "yyyy-MM-DD",
  "folderPath": "finances",
  "delimiter": ";",
  "amountFormat": "full",
  "shortcutExpenses": [
    "{\"amount\":null,\"category\":\"Mobility\",\"text\":\"Refuel\"}",
    "{\"amount\":null,\"category\":\"Groceries\",\"text\":\"XYZ Market\"}",
    "{\"amount\":8,\"category\":\"Fun\",\"text\":\"Cofe at Starbucks\"}"
  ]
}
2024-04-01 16:35:17 ❗️ERROR❗️ {}

Da: David Wertheimer ***@***.***>
Risposta: NotePlan/plugins ***@***.***>
Data: giovedì 28 marzo 2024, 18:34
A: NotePlan/plugins ***@***.***>
Cc: Annapaola Carrano ***@***.***>, Author ***@***.***>
Oggetto: Re: [NotePlan/plugins] m1well.Expenses plugin doesn't work (Issue #547)


Which of the options did you try? Individual, shortcut or fixed?

Is there anything in the plugin console when you run it?
