### ISSUE TITLE
Dashboard future feature request: Add a calendar picker

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#552]
When we move to React, it would be nice if the pop-up would let you put any date you want for the move-to/due date and you could use a calendar picker to do it. There is a really solid open-source one we can use:

https://www.npmjs.com/package/react-datepicker?ref=retool-blog.ghost.io

I obviously can help with this when the time comes.

**Comment by jgclark** [comment]
Implemented by @dwertheimer in the upcoming 2.0 release.
