### ISSUE TITLE
Dashboard: iphone view

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#553]
Since you have a responsive stylesheet, why not make an iPhone version of the dashboard? especially with multiple hashtags, etc. I would like to be able to see just my #home items when I'm home. We can address this in React if you wish.

**Comment by jgclark** [comment]
I can probably remove the iPhone restriction now we have a proper dialog box.
Though presumably you can get a long way with filters now, for your particular use case?

**Comment by jgclark** [comment]
I figured this would be a fairly simple change, so I went ahead and progressed it.
As usual, there's hidden complexity ... trying to get it (particularly the dialog box) to work well on a fairly small iPhone which I have is proving taxing. I was trying to get it to respond well to all widths, but I may have to give up and use a media query.

**Comment by dwertheimer** [comment]
"This should be quick" rarely is. :)

**Comment by jgclark** [comment]
After many hours more work than I expected, this is now released as v1.2.0.

**Comment by dwertheimer** [comment]
Thanks but sorry
