### ISSUE TITLE
Allow console.error() in HTMLViews

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#558]
- [x] I confirm I have restarted NotePlan and this problem still persists.
- [x] Is this a repeatable problem?

When developing more advanced (and more useful) plugins using HTMLViews like Dashboard the only logging option we have is console.log(). Which isn't amazing, but is OK.

But now we're making more use of the React framework, we've hit a problem. It generates console.error() messages which are (we think) currently getting swallowed up by NP and not copied into the logs. This is making development harder and slower than usual.

We want to have the ability to use console.error (and while we're at it console.info), as third party frameworks expect. 

Is there anything fundamentally stopping this?

**Comment by EduardMe** [comment]
Implemented, we can test in the next alpha (not yet uploaded).
