### ISSUE TITLE
add ability to add default #tags or @mentions to Quick Capture inbox task

### ISSUE THREAD

**Issue by bcohen44** [NotePlan/plugins#57]
User case: I currently have my Quick Capture Inbox `/int` set for my daily note.  I would like the ability in the _configuration to set default tags to _append_ the end of the task.

**Comment by jgclark** [comment]
There are several different commands provided by the Quick Capture plugin. Some are designed to add tasks; others to add more general text. Would you want this to apply to all task-adding commands, or just `/int`?

**Comment by bcohen44** [comment]
I mostly use `/int` with the day note, but I can see value for all task-entry quick captures.

**Comment by jgclark** [comment]
Added in v0.7.0
