### ISSUE TITLE
Window Helpers feature request: Open Windows Quick Switch

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#577]
I often find that I am switching between the windows in NotePlan -- Editor, Today, Dashboard, Dashboard Issues Note...what I wish I had was a keyboard shortcut that would open up a CommandBar list of the open windows so i can quickly choose the one i want to go to.
I'm thinking each one would be numbered:
1 - Editor
2 - Today (window)
3 - Dashboard (window)
4 - Dashboard 
So I always know that 1 will take me back to the Editor, and the rest, I see the number and quickly type that number in

**Comment by jgclark** [comment]
Is ⌥+Tab not quick enough for you?  I forget if it has to be turned on, but it's an OS-level action.

**Comment by dwertheimer** [comment]
I forgot about the Alt-Tab app! Re-installed it. A great solution!
