### ISSUE TITLE
Dashboard react today task completion

### ISSUE THREAD

**Issue by aaronpoweruser** [NotePlan/plugins#581]
**Checks**
- [ x] I confirm I have restarted NotePlan and this problem still persists.
- [ x] Is this a repeatable problem?

**Describe the bug**
The behavior when completing task tagged ">today" via dashboard react is not the same as when completing task via the Noteplan reference area. When the Noteplan reference area is used and a task is tagged ">today", the today tag is removed by NotePlan. Dashboard does not remove the today tag leading to the task remaining in the reference area on other daily notes.

What do you expect it to do instead?

After a task is completed the ">today" tag is removed upon completion. 

**To Reproduce**
1. In any note create a task with a ">today" tag
2. Complete task via dashboard react.
3. In note see the task completed and the ">today" tag still present.
4. Compare to task completed via reference area. 

**Screenshots**

**System**
 - Device:= All
 - OS: All
 - NotePlan Version 
 - Plugin Name & Version Dashboard react-B1

**Additional context**

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin's Preferences by going to `NotePlan's menu > Preferences > Plugins` and clicking the settings "cog" icon next to the plugin in question. Scroll to the bottom and set the logging level to "DEBUG" and click "Save & Close"
6. Now open the Plugin Console by going to `Noteplan > Help > Plugin Console` (_not_ the macOS Console app).
7. Run the plugin command you're reporting
8. Copy the output from the Plugin Console and paste it below
9. Delete any output that has personal information you don't want in there
```javascript
    PASTE_PLUGIN_CONSOLE_OUTPUT_HERE
```

**Comment by jgclark** [comment]
Please can you keep discussion of this to the invite-only Discord channel for now? That helps the others doing beta testing.

**Comment by jgclark** [comment]
I can't reproduce this. When I add `+ today test >today` to today's note, I don't see it in the Reference area on yesterday, today or tomorrow. Can you do a before/after screenshot to show this?  I can't see any NP settings that would affect this, but perhaps I'm missing something.

**Comment by jgclark** [comment]
@aaronpoweruser I've not heard back, so I'm closing this. But do use the Discord beta channel to add more details if you're still seeing the problem.
