### ISSUE TITLE
FIler: Allow for Target FIlter

### ISSUE THREAD

**Issue by mjsalam** [NotePlan/plugins#588]
Would be helpful to be able to apply a filter to the target note selection when move a line or block. 

- For example ...only show files with #project tag.

**Comment by jgclark** [comment]
What's the problem that this seeks to solve (i.e. why this "would be helpful")?

And where/when would you like to be able to apply a filter? Would it be fixed for you, or would it change?

**Comment by jgclark** [comment]
Closing, as no reply in 2 months.
