### ISSUE TITLE
Support for rescheduling via copy

### ISSUE THREAD

**Issue by tophee** [NotePlan/plugins#589]
**Is your feature request related to a problem? Please describe.**
My preferred way of rescheduling a task is to copy it (i.e. what happens when you Option-Drag the task onto a new date in the calendar. When doing so a copy of the tasks remains where it was, but it gets marked as forwarded (`- [>]`)

**Describe the solution you'd like**
It looks like the Dahsboard doesn't support this variant of rescueduling. I would like to use it, though.

**Comment by jgclark** [comment]
Dashboard already has schedule (a form of copy) already ... see the setting "Reschedule items in place, rather than move?".
At the moment under the hood it doesn't add the `[>]` marker for it, so it might not be displayed in the same way as you're expecting (depending on your theme).

**Comment by jgclark** [comment]
Out of interest, @dwertheimer, would you want to see an option for adding the [>] marker when (re)scheduling an item?

**Comment by dwertheimer** [comment]
I don’t use this feature personally because I move things so often, but
given that it is a built in option in NP, it probably makes sense to add
it.

**Comment by tophee** [comment]
> given that it is a built in option in NP, it probably makes sense to add it

I agree. There are already many ways of scheduling and rescheduling in Noteplan, which can be somewhat confusing. So, not offering yet another version (copy task without marking the original as [>]) might be beneficial.

**Comment by jgclark** [comment]
> I agree. There are already many ways of scheduling and rescheduling in Noteplan, which can be somewhat confusing. So, not offering yet another version (copy task without marking the original as [>]) might be beneficial.

Well argued. This will shortly be released as a change in v2.0.6.

**Comment by tophee** [comment]
While you're at it, call it rechedule instead of copy, so the terminology is consistent.

**Comment by jgclark** [comment]
>
> While you're at it, call it rechedule instead of copy, so the terminology
> is consistent.
>
I'm confused: where is it called 'copy' that it shouldn't be?

**Comment by tophee** [comment]
Sorry, I think I mixed up different issues.
