### ISSUE TITLE
Quick Capture 0.7.0 does not work if Inbox note is Daily Note, aka "" in config

### ISSUE THREAD

**Issue by bcohen44** [NotePlan/plugins#66]
**Describe the bug**
When I configure Quick Capture to use my Daily Note as the "Inbox " note, the plugin still looks for an Inbox note.

**To Reproduce**
1.  Set ` inboxTitle: "",` in the _configuration file

**Expected behavior**
task is appended/prepended in Day Note

**Screenshots**
![CleanShot 2021-08-30 at 11 26 57](https://user-images.githubusercontent.com/6190190/131363930-4417b3fc-bcb6-4935-9f3a-f5e1e45d5cb0.png)

**System**
 - Device: Mac
 - OS: 11.5.2
 - NotePlan Version 3.1
 - Plugin Name & Version Quick Capture 0.7.0

**Additional context**
my _configuration
```  inbox: {
      inboxTitle: "", // name of your inbox note, or leave empty ("") to use the daily note instead. (If the setting is missing, or doesn't match a note, then the plugin will try to create it, from default settings if necessary.)
	addInboxPosition: "prepend",  // or "append"
   textToAppendToTasks: "#Inbox"
	},```

**Comment by jgclark** [comment]
Sorry about that, @bcohen44. Fix will be available shortly.
