### ISSUE TITLE
Split up helperFunctions into smaller units

### ISSUE THREAD

**Issue by jgclark** [NotePlan/plugins#71]
After some Discord discussion, we have decided to break up the increasingly lengthy helperFunctions.js file to more useful and obvious files in a new `helpers` folder:
- dateFunctions.js
- noteFunctions.js
- pararagraphFunctions.js
- userInput.js
- otherFunctions.js [for ones that don't fit elsewhere]

**Comment by dwertheimer** [comment]
Yes but with the @codedungeon shorter names. :)

**Comment by mikeerickson** [comment]
Ya, we can drop the “functions” from name.

`helpers/dateTime.js`
`helpers/general.js` 
`helpers/userInput.js`
`helpers/paragraph.js`
`helpers/note.js`

**Comment by jgclark** [comment]
This won't be the end of the story on helper functions, but I'm assuming we can now close this after the main work here was done last week. Please reopen if need be, @dwertheimer or @mikeerickson.
