### ISSUE TITLE
(low priority) pickDate and pickDateInterval - would be nice if they would run without params in template mode

### ISSUE THREAD

**Issue by dwertheimer** [NotePlan/plugins#74]
@jgclark I have a Templates test script and I test all the templates after I touch that code.
The new pickDate and pickDateInterval doesn't run perfectly without params. Would be good if it provided feedback.

![Screen Shot 2021-09-03 at 5 26 57 PM](https://user-images.githubusercontent.com/8949588/132078878-7be17ffe-a344-48da-8720-11ef555c5053.jpg)

```js
# Template Tester
---

## Today:
8601 date the hard way:
- {{date({locale: 'sv-SE', dateStyle: 'short'})}}
Formatted:
- {{formattedDateTime('%Y-%m-%d %I:%M:%S %P')}}
8601 the easy way:
- {{date8601()}}
pickdate:
- {{pickDate()}}
- {{pickDateInterval()}}
week span:
- {{weekDates()}}
- {{weekDates({startMonday:false, format:`%Y-%m-%d`})}}
- {{weekDates({startMonday:true, format:`%Y-%m-%d`})}}
meetingName tag:
- {{meetingName}}
weather:
- {{weather()}} 
quote:
- {{quote()}} 
Tasks last 7 days with headings (with confirmation):
- {{sweepTasks({limit:{ "unit": "day", "num":1 },includeHeadings:true,requireConfirmation:true})}}
---
Events:
{{listTodaysEvents({template:"- *|START|*-*|END|*: *|TITLE|*",allday_template:"- *|TITLE|*"})}} ---
Matching events:
{{listMatchingEvents()}} -- (requires configuration)
```

**Comment by jgclark** [comment]
@dwertheimer, I have now provided default questions for each. Please review PR to see if that does what you hope. 
(I'm not wanting to make it smarter that this, as I hope it will be replaced soon by new API calls from Eduard.)

**Comment by jgclark** [comment]
It's been a week, so closing this one.
