### ISSUE TITLE
Calendar filtering for EventHelpers and Templates

### ISSUE THREAD

**Issue by brentonmallen1** [NotePlan/plugins#84]
**Is your feature request related to a problem? Please describe.**
When making a list of the days events in a template, all calendar events are populated.  This makes it difficult to isolate the list to a particular calendar; for example work vs personal.

**Describe the solution you'd like**
I'd like to be able to apply a filter along the same likes as Matching Events [here](https://github.com/NotePlan/plugins/tree/main/nmn.Templates#events--listmatchingevents----using-event-lists-from-a-template) to filter down to a calendar/set of calendars of interest.

**Describe alternatives you've considered**
The only alternative I can think of is to limit the calendars that are imported into the application but that degrades the utility of the events sidebar.

**Comment by jgclark** [comment]
Thanks. I think this is good addition to have, and the API support to make it possible is now there. The challenge will be in making it not too complicated.

**Comment by jgclark** [comment]
Should be delivered by #90, so closing.
Please open again if there are problems.
