### ISSUE TITLE
Plugin Update Notification

### ISSUE THREAD

**Issue by brentonmallen1** [NotePlan/plugins#85]
**Is your feature request related to a problem? Please describe.**
When exploring templating, I was running into unexpected errors due to, what I figured out after some time, my plugins were not updated.

**Describe the solution you'd like**
I'd like to receive a notification that there are updates available for my selected plugins somewhere in the app that is readily apparent.

**Describe alternatives you've considered**
The only thing I can think of to try would be to regularly check the plugins panel but that requires being proactive which isn't ideal as a user

**Comment by jgclark** [comment]
Good news: the NP developer recently added to his roadmap something to help make it more obvious when there are plugin updates.
But in the meantime, you can look in the Discord channel #plugin-updates, where they all get notified.
