### ISSUE TITLE
Filer Error

### ISSUE THREAD

**Issue by joshuasblanchard** [NotePlan/plugins#87]
**Describe the bug**
Since updating to 10.3, I receive "Invalid JSON5 in your configuration" message on both MacBook and iPad. Deleted and recreated configuration note. Same error message.

**To Reproduce**
1. cmd+j
2. /fp
3. Enter

**Expected behavior**
Move paragraph to note

**System**
 - Device: Macbook & iPad
 - OS: MacOS 11.6, iPadOS 14.8
 - NotePlan Version: 3.0.26
 - Plugin Name & Version: Filer V0.5.0

**Plugin Console Log**
To provide us with more clues about where the bug/error is occurring...
1. Open the Plugin Console by going to `Noteplan > Help > Plugin Console`
1. Run the plugin you're reporting
1. Copy the output from the Plugin Console and paste it below
1. Delete any output that has personal information you don't want in there
```javascript
JSLog:   getOrMakeConfigurationSection: got folder 📋 Templates
JSLog:   getOrMakeConfigurationSection: got _configuration file
JSLog: SyntaxError: JSON5: invalid character 'i' at 2:4```

**Comment by mikeerickson** [comment]
@joshuasblanchard Could you please supply a copy of your `_configuration` note so that we can review and determine where the error is located.

**Comment by joshuasblanchard** [comment]
#  _configuration
---
# Template Tag Configuration

This note provides a central location where you can configure various plugin options:

- Use the fenced code block below (which comes after a line made by 3 dashes) to customize global values for the various template tags.

- NotePlan plugin configuration uses JSON5 [JSON5 | JSON for Humans](https://json5.org/), which is a human-friendly superset of JSON, providing things such as comments, unquoted keys and other common patterns available in standard JavaScript objects.

	*Note: Despite JSON5 enhancements, multi-line strings are not supported, therefore to include*
	*them you need to use "\n" (new line) for line breaks rather than actual line breaks.*

- Use the code block marked as `javascript` shown below to write your own custom custom configurations.

While it is possible to have multiple `javascript` code blocks in this document, only the **first** code block will be used.

## Validating Configuration
The configuration code blocks below are validated in **realtime** by NotePlan as you edit:

- If there is a configuration mistake, all code below will all be a single color (based on theme).
- If the configuration passes the validation, you will see configuration settings will be formatted based on your current theme (e.g., orange, green, purple, black, etc.).

**TIP:** If your configuration is invalid, you can copy/paste the configuration block to [JSON5 Validator Online - JSON5 lint Tool to validate JSON5 data](https://codebeautify.org/json5-validator) which will provide details about the error(s) in your code block, indicating which line(s) contain the error(s).

### Line Breaks
If you have a quoted "string" which you want to have a line break, insert a "\n" where you want the line break, e.g., "This\nIs\nThreelines"

### Reporting Plugin Issues
Should you run into an issue with a NotePlan plugin, you can use one of the following methods (in order of priority)

🐞 [NotePlan Plugin Issues](https://github.com/NotePlan/plugins/issues/new/choose)
🧩 [Discord](https://discord.com/channels/763107030223290449/784376250771832843)
📪 [NotePlan ***@***.***)
*****
## Plugin Configuration
*Note: While the following code block is marked as `javascript` it is actually `JSON5` and is only marked as `javascript` so that your theme will provide the appropriate syntax highlighting.*

```javascript

  filer: {
    addDateBacklink: true, // whether to insert date link in place of the moved text
  },


{
  // Note Even though it is fenced as "javascript", this configuration is actually JSON5.

  // configuration for dates, heavily based on javascript's Intl module
  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

  date: {
    // Default timezone for date and time.
    timezone: 'automatic',
    // Default locale to format date and time.
    // e.g. en-US will result in mm/dd/yyyy, while en_GB will be dd/mm/yyyy
    locale: 'en-US',
    // can be "short", "medium", "long" or "full"
    dateStyle: 'short',
    // optional key, can be "short", "medium", "long" or "full"
    timeStyle: 'short',
    // time format when invoking dwertheimer.DateAutomations/formatted
    // see https://www.strfti.me/ to aid in creating custom formats)
    format: '%Y-%m-%d %I:%M:%S %P'
  },


  // configuration for weather data (used in Daily Note Template, for example)
  weather: {
    // API key for https://openweathermap.org/
    // !!REQUIRED!!
    openWeatherAPIKey: '... put your API key here ...',
    // Required location for weather forecast
    latPosition: 0.0,
    longPosition: 0.0,
    // Default units. Can be 'metric' (for Celsius), or 'imperial' (for Fahrenheit)
    openWeatherUnits: 'metric',
  },


  // configuration for daily quote (used in Daily Note Template, for example)
  quote: {
    // Available modes: [random (default), today, author]
    mode: 'today',
    // API key required, available authors: https://premium.zenquotes.io/available-authors/
    author: 'anne-frank',
    // Required for mode: 'author' (from https://premium.zenquotes.io/)
    apiKey: '... put your API key here ...',
  },


  // default values for custom tags.
  // These tags cannot be functions, but you may choose to have nested objects.
  // feel free to edit this value however you see fit.
  tagValue: {
    me: {
      // Can be used as {{me.firstName}}
      firstName: 'John',
      // Can be used as {{me.lastName}}
      lastName: 'Doe',
    }
    // ...
  },
}

```

**Comment by jgclark** [comment]
Ah, this is an easy one, I think.
There was a period of a week or so where someone introduced a very subtle bug in the Template framework which meant it didn't set the configuration file correctly. If you know JSON you can see that the codeblock doesn't start properly. The first part should read:

```
```javascript
{
  // Note Even though it is fenced as "javascript", this configuration is actually JSON5.

  filer: {
    addDateBacklink: true, // whether to insert date link in place of the moved text
  },
...
```

**Comment by joshuasblanchard** [comment]
Thank you, replacing those lines fixed the error.
